/* Product data for the /software section — facts sourced from each repo's README */
module.exports = [
  {
    slug: 'pdfsmith', brand: 'PDFsmith', repo: 'pdf-toolkit', price: 29, icon: '📄',
    tagline: 'Every PDF tool you actually use — running 100% on your machine.',
    oneliner: 'Merge, split, rotate, watermark & convert PDFs offline. No uploads, ever.',
    competitor: 'SmallPDF', compPrice: '$12–15/mo', compYr: 144,
    heroLead: 'SmallPDF charges up to $15/month, forever, to do things your computer can do for free — and it uploads your documents to their servers to do it. PDFsmith does the same jobs locally, offline, with zero telemetry, for a one-time $29.',
    features: [
      ['🔗', 'Merge PDFs', 'Drag-drop any number of PDFs, reorder them in the list, combine into one file.'],
      ['✂️', 'Split PDF', 'Extract any page ranges (1-2 | 3 | 4-6) into separate new PDFs.'],
      ['🔄', 'Rotate pages', '90° / 180° / 270°, all pages or a specific range, batched across files.'],
      ['💧', 'Watermark', 'Text (position, size, opacity, diagonal) or image stamp — batch across files.'],
      ['🖼️', 'Images → PDF', 'JPG/PNG to PDF, one image per page, reorderable, A4-fit or native size.'],
      ['🏷️', 'Metadata editor', 'Read and rewrite title, author and subject — something SmallPDF doesn\'t even offer.'],
      ['🔒', '100% offline', 'All processing happens locally with pdf-lib. No network calls, no uploads, no account.'],
      ['🧾', 'No telemetry', 'Your contracts, invoices and records never leave your disk. Zero analytics.'],
    ],
    compRows: [
      ['Price', '$29 once', '$12–15/month ($144+/yr, forever)'],
      ['Your files', 'Never leave your machine', 'Uploaded to their servers'],
      ['Works offline', 'Yes', 'No'],
      ['Account required', 'No', 'Yes'],
      ['Merge / split / rotate', 'Yes', 'Yes'],
      ['Watermark (text + image)', 'Yes', 'Pro only'],
      ['Metadata editor', 'Yes', 'No'],
      ['Source code', 'MIT, on GitHub', 'Closed'],
    ],
    payback: 'Two and a half months of SmallPDF pays for PDFsmith outright. Everything after that is money you keep.',
    steps: [
      ['Buy once on Whop', 'One-time $29. You get the signed Windows installer — no account with us, no subscription to remember to cancel.'],
      ['Install in one click', 'Run the installer. No Node, no terminal, no setup. The app opens straight to the tools.'],
      ['Drop in your PDFs', 'Merge, split, rotate, watermark or convert — everything happens on your machine, instantly, offline.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes. The full source code is MIT-licensed at github.com/bensblueprints/pdf-toolkit and always will be. Buying gets you the signed Windows installer, 1-click setup and updates — pure convenience, zero lock-in.'],
      ['Do my PDFs get uploaded anywhere?', 'No. All processing runs locally with pdf-lib, a pure-JavaScript library. The app makes no network calls at all — you can run it with Wi-Fi off.'],
      ['What platforms does it run on?', 'The packaged installer is for Windows. The MIT source runs anywhere Electron does (Windows, macOS, Linux) if you build it yourself with Node 18+.'],
      ['Can it edit text inside a PDF?', 'No — and we\'d rather tell you that upfront. PDFsmith covers merge, split, rotate, watermark, images-to-PDF and metadata. For rewriting body text inside an existing PDF you still need a full editor like Acrobat.'],
      ['Is this a subscription in disguise?', 'No. $29 once. No renewal, no license server phoning home, no "lifetime deal" fine print. The app keeps working forever, even offline.'],
    ],
  },
  {
    slug: 'cutaway', brand: 'Cutaway', repo: 'bg-remover', price: 24, icon: '🪄',
    tagline: 'Remove image backgrounds with local AI. Unlimited images, full resolution, zero uploads.',
    oneliner: 'Local AI background removal — unlimited images, full resolution, nothing uploaded.',
    competitor: 'remove.bg', compPrice: '$9/mo (40 credits)', compYr: 108,
    heroLead: 'remove.bg charges $9/month for 40 credits — and every photo you upload goes to their servers. Cutaway runs the same class of AI model on your own machine: no credits, no upload, no monthly bill, no resolution cap.',
    features: [
      ['🖱️', 'Drag & drop batches', 'Single images or whole folders — JPG, PNG and WebP.'],
      ['👁️', 'Before / after preview', 'Checkerboard view of the transparent result, per image.'],
      ['🎨', 'Flexible output', 'Transparent PNG, white/black, or any custom background color.'],
      ['📦', 'Batch export', 'Pick a folder, hit one button, watch the progress bar.'],
      ['🔍', 'Full resolution, always', 'Your 6000×4000 photo stays 6000×4000. remove.bg\'s free tier caps at 0.25 MP.'],
      ['🔒', '100% private', 'The AI model (ONNX, U²-Net family) runs locally. Images never leave your computer.'],
      ['🧠', 'One-time model download', 'The ~80 MB AI model downloads once on first use — then everything works fully offline.'],
      ['🛡️', 'Memory-safe queue', 'Images process sequentially in an isolated worker, so a 40-image batch never freezes the UI.'],
    ],
    compRows: [
      ['Price', '$24 once', '$9/mo (40 credits) — $108/yr'],
      ['Images', 'Unlimited', '40/month, then buy credits'],
      ['Resolution', 'Full, always', 'Full res costs 1 credit per image'],
      ['Privacy', '100% local — nothing uploaded', 'Every image uploaded to their servers'],
      ['Offline', 'Yes (after one-time model download)', 'No'],
      ['Batch processing', 'Yes, built in', 'Paid API / desktop app with credits'],
      ['Source code', 'Open (MIT)', 'Closed'],
    ],
    payback: '$24 pays for itself in under 3 months — then it\'s free forever.',
    steps: [
      ['Buy once on Whop', 'One-time $24 gets you the packaged Windows installer with 1-click setup and updates.'],
      ['First run downloads the AI', 'The ~80 MB model downloads once, clearly shown in the UI. After that Cutaway is fully offline.'],
      ['Drop images, export cutouts', 'Batch a whole product shoot, preview each result, export transparent PNGs to any folder.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — the full source is MIT at github.com/bensblueprints/bg-remover. Paying $24 gets you the signed installer, 1-click setup and updates instead of building from source.'],
      ['Is the quality as good as remove.bg?', 'It uses the same class of segmentation model (U²-Net family via ONNX). On typical product shots and portraits results are comparable; on very fine edges like wispy hair, remove.bg\'s newest cloud models can still win. You get unlimited retries for free, though.'],
      ['Do my photos get uploaded?', 'Never. Inference runs on your CPU via onnxruntime. The only network call the app ever makes is the one-time model download.'],
      ['Is it fast?', 'It runs on your own hardware, one image at a time by design (predictable memory). A batch takes a few seconds per image on a modern CPU — no queue, no credits, no per-image anxiety.'],
      ['What formats are supported?', 'JPG, PNG and WebP in; transparent PNG or flat-color composites out, at the original resolution.'],
    ],
  },
  {
    slug: 'whisperdesk', brand: 'WhisperDesk', repo: 'whisper-transcriber', price: 39, icon: '🎙️',
    tagline: 'Unlimited local audio & video transcription. Your audio never leaves your machine.',
    oneliner: 'Whisper-powered transcription on your own CPU — unlimited minutes, TXT/SRT/VTT export.',
    competitor: 'Otter.ai', compPrice: '$16.99/mo', compYr: 204,
    heroLead: 'WhisperDesk does what Otter.ai charges $16.99/month for — but 100% locally, powered by whisper.cpp (OpenAI\'s Whisper model running natively on your CPU). Drop in any audio or video file, get back an accurate, timestamped transcript. No upload, no account, no per-minute limits.',
    features: [
      ['🎧', 'Drag & drop anything', 'mp3, wav, m4a, mp4, mov, mkv, flac, ogg, webm — video audio is extracted automatically.'],
      ['🔒', '100% private', 'Transcription runs entirely on your machine. Nothing is ever uploaded.'],
      ['♾️', 'Unlimited minutes', 'No cap, no monthly quota. Transcribe 10 hours a day if you want.'],
      ['🧠', 'Model picker', 'Tiny / base / small / medium, English-only or multilingual — downloaded once from Hugging Face.'],
      ['🌍', 'Language auto-detect', 'Or force English. Multilingual models cover dozens of languages.'],
      ['📊', 'Live progress', 'Real-time percentage while Whisper works, with timestamped transcript view and one-click copy.'],
      ['💾', 'Export TXT, SRT, VTT', 'Ready for subtitles, notes, or your editor.'],
      ['🕘', 'Local history', 'Every transcription saved locally — reload it any time.'],
    ],
    compRows: [
      ['Price', '$39 one-time', '$16.99/month, forever'],
      ['Cost after 1 year', '$39', '~$204'],
      ['Transcription limit', 'Unlimited', '1,200 min/mo (Pro)'],
      ['Max file length', 'Unlimited', '90 min per conversation'],
      ['Privacy', 'Audio never leaves your PC', 'Uploaded to their cloud'],
      ['Works offline', 'Yes', 'No'],
      ['Video files', 'Yes (audio auto-extracted)', 'Limited'],
      ['SRT/VTT subtitle export', 'Yes', 'Paid tiers'],
    ],
    payback: 'Pays for itself in under 3 months of Otter.ai Pro.',
    steps: [
      ['Buy once on Whop', 'One-time $39 for the packaged Windows installer — no terminal, no build step.'],
      ['Pick a model', 'On first run WhisperDesk fetches whisper.cpp (~8 MB) and your chosen model (78–148+ MB) with a visible progress bar. One time only.'],
      ['Drop a file, get a transcript', 'Timestamped text in minutes, exportable as TXT, SRT or VTT — all offline.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT-licensed at github.com/bensblueprints/whisper-transcriber, and it always will be. The $39 buys the signed installer, 1-click setup and updates.'],
      ['How accurate is it?', 'It runs OpenAI\'s Whisper models — the same family behind most modern transcription tools. Bigger models (small/medium) are more accurate and slower; you pick the trade-off.'],
      ['Does it do live meeting transcription?', 'No — and Otter is genuinely better for that. WhisperDesk transcribes files (recordings, interviews, videos, podcasts). If you need a live meeting assistant with speaker chat, keep Otter.'],
      ['How fast is it?', 'Depends on your CPU and model size. The tiny/base models typically run faster than real time on a modern machine; medium trades speed for accuracy.'],
      ['Does it need the internet?', 'Only twice, ever: the one-time whisper.cpp binary download and your chosen model from Hugging Face. After that it\'s fully offline.'],
    ],
  },
  {
    slug: 'shrinkray', brand: 'Shrinkray', repo: 'image-compressor', price: 19, icon: '🗜️',
    tagline: 'Unlimited local batch image compression & conversion.',
    oneliner: 'Batch-compress a thousand photos locally — JPG, PNG, WebP, AVIF — no upload limits.',
    competitor: 'TinyPNG Pro', compPrice: '~$39/yr + API fees', compYr: 39,
    heroLead: 'Stop uploading your images to random websites 20 at a time. Shrinkray runs 100% on your machine — drag in a thousand photos, pick a quality, and watch the megabytes melt away. No upload limits, no monthly bill, no cloud, no telemetry.',
    features: [
      ['🖼️', 'Drag & drop batches', 'JPG, PNG, WebP, AVIF, TIFF. Drop a whole shoot at once.'],
      ['📉', 'Live savings dashboard', 'Per-file and total before → after sizes with animated counters and % saved.'],
      ['🎚️', 'Quality slider', 'Full 1–100 control, powered by mozjpeg-grade encoders via sharp (libvips).'],
      ['🔁', 'Format conversion', 'Keep the original format, or convert everything to JPG, PNG, WebP or AVIF in one pass.'],
      ['📐', 'Max-dimension resize', 'Cap the longest edge for web exports — without upscaling.'],
      ['📁', 'Flexible output', 'Write to a chosen folder or alongside originals with a _compressed suffix. Originals are never touched.'],
      ['💾', 'Settings persist', 'Quality, format and output preferences remembered between sessions.'],
      ['🔒', '100% local', 'Zero network calls. Client photos and product shots never leave your disk.'],
    ],
    compRows: [
      ['Price', '$19 once', 'Subscription + per-image API fees at volume'],
      ['Upload limits', 'None — it\'s your CPU', 'Capped per month / per file size'],
      ['Max file size', 'Whatever your RAM handles', '75 MB cap'],
      ['Batch size', 'Unlimited', 'Limited per batch'],
      ['Formats', 'JPG, PNG, WebP, AVIF, TIFF', 'JPG, PNG, WebP, AVIF'],
      ['Privacy', 'Images never leave your machine', 'Every image uploaded to their servers'],
      ['Works offline', 'Yes', 'No'],
      ['Open source', 'Yes (MIT)', 'No'],
    ],
    payback: 'Pay for a few months of any subscription compressor and you\'ve already spent more than Shrinkray costs — and you still won\'t own anything.',
    steps: [
      ['Buy once on Whop', 'One-time $19 — the cheapest app in the suite, and probably the one you\'ll use most.'],
      ['Install in one click', 'Signed Windows installer. sharp ships prebuilt — nothing to compile, nothing to configure.'],
      ['Drop a folder, export', 'Set quality and format once; settings persist. Watch the savings counter climb.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/image-compressor. $19 gets you the signed installer, 1-click setup and updates.'],
      ['Is the compression as good as TinyPNG?', 'It uses sharp/libvips with mozjpeg-grade encoders — the same engines behind most professional pipelines. At equal quality settings, results are comparable; you also get AVIF, which typically beats PNG/JPG sizes outright.'],
      ['Will it overwrite my originals?', 'Never. Output goes to a folder you choose, or next to originals with a _compressed suffix.'],
      ['Is there an API or CLI?', 'Not in the app — it\'s a desktop tool. The MIT source exposes the pure-Node compression pipeline if you want to script it.'],
      ['Does it phone home?', 'No. Zero network calls, zero telemetry, no account. You can verify that in the source.'],
    ],
  },
  {
    slug: 'clipdeck', brand: 'ClipDeck', repo: 'screen-recorder-desktop', price: 29, icon: '🎥',
    tagline: 'The Loom replacement you buy once. Record, trim, export MP4 or GIF — all local.',
    oneliner: 'Screen + mic recording with local library, MP4 & two-pass GIF export. No cloud.',
    competitor: 'Loom', compPrice: '$15/mo', compYr: 180,
    heroLead: 'Record your screen and mic, save everything locally, export MP4 or GIF — no cloud, no monthly bill, no watermark, no upload limits. Your recordings live on your disk, not on someone else\'s server.',
    features: [
      ['🖥️', 'Source picker with live previews', 'Record any screen or individual window — thumbnails included.'],
      ['🎤', 'Microphone audio', 'One toggle, mixed cleanly with system audio into a single track.'],
      ['⏺️', 'Floating recording pill', 'Tiny always-on-top timer with a stop button, so the main window stays out of the shot.'],
      ['📚', 'Local library', 'Every recording auto-saves to Videos/Screen Recorder with thumbnails, and plays right in the app.'],
      ['🎬', 'MP4 export', 'H.264 + faststart — plays everywhere, with live progress.'],
      ['🌀', 'Optimized GIF export', 'Proper two-pass palette generation, not the muddy single-pass junk.'],
      ['✂️', 'Trim', 'Set start/end before exporting — no separate editor needed.'],
      ['🔒', '100% local', 'Zero telemetry, zero network calls, zero accounts, zero watermarks.'],
    ],
    compRows: [
      ['Price', '$29 once', '$15/mo, forever ($180/yr)'],
      ['Where videos live', 'Your disk', 'Their servers'],
      ['Recording length', 'Unlimited', 'Limited by plan'],
      ['Watermark', 'Never', 'On free tier'],
      ['Works offline', 'Yes', 'No'],
      ['Account required', 'No', 'Yes'],
      ['MP4 + GIF export', 'Built in', 'GIF gated by plan'],
      ['Your data mined for AI', 'Impossible — it never leaves', 'Read the ToS'],
    ],
    payback: 'Loom Business is $180/yr. ClipDeck is $29 once — it pays for itself in under 2 months.',
    steps: [
      ['Buy once on Whop', 'One-time $29 for the packaged installer, free updates forever.'],
      ['Pick a screen or window', 'Live-preview source picker, mic toggle, hit record. A floating pill keeps the timer out of your shot.'],
      ['Trim & export', 'MP4 for sharing anywhere, or a properly-paletted GIF for docs and PRs. Files stay in your Videos folder.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/screen-recorder-desktop. $29 buys the signed installer, 1-click setup and updates.'],
      ['Does it upload my videos anywhere?', 'No. There is no cloud. Recordings save to your Videos folder and never leave it unless you share them yourself.'],
      ['Can I share a link like Loom?', 'Not built in — that\'s the honest trade-off. Loom\'s instant share-link is its killer feature. ClipDeck gives you the file; share it via Drive, Slack or your own hosting.'],
      ['Does it record webcam?', 'It records screen or window plus microphone. A webcam overlay isn\'t in the current feature set — if that\'s essential, Loom or OBS may fit better.'],
      ['What about recording length limits?', 'None. Record until your disk is full.'],
    ],
  },
  {
    slug: 'upwatch', brand: 'Upwatch', repo: 'uptime-monitor', price: 39, icon: '📡',
    tagline: 'Self-hosted uptime monitoring + a beautiful public status page.',
    oneliner: 'HTTP checks, incident log, alerts and a branded 90-day status page — on your own box.',
    competitor: 'UptimeRobot', compPrice: '$8/mo', compYr: 96,
    heroLead: 'UptimeRobot charges $8/mo. Pingdom starts at $10/mo. Both cap your monitors and keep billing you forever. Upwatch is the same core product — HTTP checks, incident tracking, alerting, a classic 90-day-bar status page — running on your own $5 VPS (or your desktop) with unlimited monitors and zero recurring fees.',
    features: [
      ['🌐', 'HTTP(S) monitors', 'URL, interval from 30s to 15m, expected status code, optional keyword match.'],
      ['⚙️', 'In-process checker loop', 'No cron, no workers, no Redis — one Node process does everything.'],
      ['🗄️', 'SQLite storage', 'Check history with automatic 90-day retention pruning. One file to back up.'],
      ['📈', 'Per-monitor detail', 'Uptime % for 24h / 7d / 30d, response-time sparkline, full incident log.'],
      ['🟢', 'Public status page', 'Clean branded page at /status — per-monitor badges, classic 90-day uptime bars, outage banner.'],
      ['🔔', 'Alerts on down + recovery', 'Slack/Discord-compatible JSON webhook and email via your own SMTP.'],
      ['🏢', 'Built for agencies', 'Monitor every client site from one box; hand clients a clean branded status page.'],
      ['🖥️', 'Desktop or VPS', 'Run it as a desktop app, or deploy to a $5 VPS (Docker included) when it needs to be public.'],
    ],
    compRows: [
      ['Price', '$39 once', 'UptimeRobot $8/mo ($96/yr) · Pingdom $10+/mo'],
      ['Monitors', 'Unlimited', '50 on UptimeRobot\'s paid tier'],
      ['Check interval', '30s', '60s (paid)'],
      ['Public status page', 'Included, branded', 'Limited / upsell'],
      ['Keyword checks', 'Included', 'Paid tier'],
      ['Your data', 'Your SQLite file on your box', 'Their cloud'],
      ['Multi-client agency use', 'One VPS monitors everything', 'Per-account limits / pricing'],
    ],
    payback: 'Pays for itself vs UptimeRobot in under 5 months — then it\'s free forever.',
    steps: [
      ['Buy once on Whop', 'One-time $39 for the packaged, zero-config version with updates and priority support.'],
      ['Run it anywhere', 'Desktop app for personal use, or docker compose up on a $5 VPS for a public status page.'],
      ['Add monitors, get alerts', 'HTTP checks every 30s, webhook/email pings the second something breaks — and again when it recovers.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/uptime-monitor, always. The paid version is pure convenience: packaged installer, updates, priority support.'],
      ['Do I need a server?', 'Not necessarily. Desktop mode runs the whole app in an Electron window. For a public status page or 24/7 monitoring you\'ll want a $5 VPS — which is still cheaper per year than one month of most competitors\' higher tiers.'],
      ['What check types are supported?', 'HTTP(S) with status-code and keyword assertions. No ping/port/DNS checks yet — if you need those today, UptimeRobot still has the broader check menu.'],
      ['Where does monitoring run from?', 'From wherever you host it — one location. Cloud services check from multiple regions; that\'s their genuine advantage. For "is my site up and is checkout on the page", one good vantage point covers it.'],
      ['How do alerts work?', 'JSON webhooks (Slack/Discord-compatible) plus email through your own SMTP credentials, on both down and recovery.'],
    ],
  },
  {
    slug: 'trimly', brand: 'Trimly', repo: 'link-shortener', price: 29, icon: '🔗',
    tagline: 'Your own branded link shortener with full click analytics.',
    oneliner: 'Branded short links, QR codes and click analytics — on your domain, in your SQLite file.',
    competitor: 'Bitly', compPrice: '$29/mo', compYr: 348,
    heroLead: 'Bitly charges $348/year just to use your own domain with your links — and your click data lives on their servers. Trimly runs on your $5 VPS (or right on your desktop), keeps every click in a local SQLite file you own, and never phones home.',
    features: [
      ['🏷️', 'Branded short links', 'Auto-generated or custom slugs on your own domain.'],
      ['📊', 'Click analytics', 'Total + unique clicks, clicks-over-time chart, top referrers, devices, browsers, countries.'],
      ['🔲', 'QR code for every link', 'Downloadable PNG and SVG.'],
      ['↪️', '301 / 302 per link', 'SEO-permanent or trackable-temporary — your call, editable any time.'],
      ['🧰', 'UTM builder', 'Built into the create form — tag campaigns without a spreadsheet.'],
      ['📥', 'Bulk CSV import & export', 'Migrate off Bitly in one paste.'],
      ['🌍', 'Country detection, zero paid APIs', 'Reads CF-IPCountry behind free Cloudflare; degrades gracefully otherwise.'],
      ['🔒', '100% local & private', 'SQLite storage, no telemetry, no tracking pixels, no external calls.'],
    ],
    compRows: [
      ['Price', '$29 once', '$29/mo ($348/yr) for a custom domain'],
      ['Your own domain', 'Included', 'Paid plans only'],
      ['Links', 'Unlimited', 'Capped per plan'],
      ['Click data ownership', 'Your SQLite file', 'Their servers'],
      ['QR codes (PNG + SVG)', 'Included', 'Limited / paid tiers'],
      ['Bulk CSV import/export', 'Yes', 'Paid tiers'],
      ['Tracking pixels / telemetry', 'None', 'Their business model'],
    ],
    payback: 'One month of Bitly\'s custom-domain plan costs the same as Trimly does once.',
    steps: [
      ['Buy once on Whop', 'One-time $29 — installer, updates and setup support included.'],
      ['Point your domain', 'Deploy to a $5 VPS with Docker, point go.yourbrand.com at it, put free Cloudflare in front for country analytics.'],
      ['Create links, watch clicks', 'Custom slugs, UTM builder, QR codes, and a full analytics dashboard you own.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/link-shortener. The $29 buys the packaged 1-click installer, updates and setup support.'],
      ['Do I need a server for public links?', 'Yes — public short links need a public host, so budget a $5/mo VPS. Desktop mode works fully offline for QR generation and campaign planning. Even VPS + Trimly year one costs less than 3 months of Bitly.'],
      ['Can I migrate from Bitly?', 'Yes — bulk CSV import is built in. Export from Bitly, paste, done. Printed QR codes keep working because destinations stay editable.'],
      ['How accurate is the geo data?', 'Country detection reads Cloudflare\'s free CF-IPCountry header — no paid geo API. Without Cloudflare in front, country data degrades gracefully to unknown.'],
      ['Is there click fraud / bot filtering?', 'Uniques use a privacy-friendly daily IP+UA hash, which de-dupes repeat visitors. There\'s no enterprise-grade bot scoring — Bitly\'s bigger plans do more there.'],
    ],
  },
  {
    slug: 'billcraft', brand: 'Billcraft', repo: 'invoice-generator', price: 39, icon: '🧾',
    tagline: 'Self-hosted invoicing for freelancers and small businesses.',
    oneliner: 'Clients, invoices, PDFs, share links & recurring billing — on hardware you control.',
    competitor: 'FreshBooks', compPrice: '$19/mo', compYr: 228,
    heroLead: 'FreshBooks charges $19/month, forever, to store your client list and send your invoices from their servers. Billcraft is the same core workflow — clients, invoices, PDFs, shareable payment links, recurring billing — running entirely on your machine (or your $5 VPS).',
    features: [
      ['🏢', 'Business profile', 'Name, logo, address, tax ID, currency and payment/bank instructions printed on every invoice.'],
      ['👥', 'Unlimited clients', 'Full CRUD with company, email, address, notes. FreshBooks Lite caps you at 5 billable clients.'],
      ['🧾', 'Real invoices', 'Line items (qty × rate), tax %, discount %, notes, due dates, configurable numbering.'],
      ['📄', 'Professional PDFs', 'Clean server-side template (pdfkit — no headless browser) with your logo and status pill.'],
      ['🔗', 'Public share links', 'Clients open /inv/<token>, see a polished invoice page, download the PDF — no login.'],
      ['📊', 'Dashboard', 'Outstanding total, paid this month, overdue list at a glance — overdue computed automatically.'],
      ['🔁', 'Recurring invoices', 'Monthly templates auto-create drafts; optionally auto-email them via your SMTP.'],
      ['🔒', '100% local', 'SQLite database, no telemetry, no external services. Your client data stays yours.'],
    ],
    compRows: [
      ['Price', '$39 once', '$19/month ($228/yr)'],
      ['Clients', 'Unlimited', '5 billable clients (Lite)'],
      ['Your data', 'On your machine/server', 'Their cloud'],
      ['Invoices + PDF + share links', 'Yes', 'Yes'],
      ['Recurring invoices', 'Yes', 'Yes'],
      ['Email via your own SMTP', 'Yes', 'No (their sender)'],
      ['Works offline (desktop mode)', 'Yes', 'No'],
      ['Source code', 'MIT, yours', 'Closed'],
    ],
    payback: 'Two months of FreshBooks pays for Billcraft outright. Everything after that is free, forever.',
    steps: [
      ['Buy once on Whop', 'One-time $39 for the packaged Windows installer — zero terminal time.'],
      ['Set up your business profile', 'Logo, tax ID, numbering, payment instructions — printed on every invoice automatically.'],
      ['Invoice and get paid', 'Send polished PDF invoices or share links; recurring templates handle your retainers.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/invoice-generator. $39 gets you the signed installer, 1-click setup and updates.'],
      ['Does it do accounting / bookkeeping?', 'No — and that matters. Billcraft is invoicing: clients, invoices, PDFs, recurring billing. FreshBooks also does expenses, time tracking and accounting reports. If you need double-entry books, keep an accounting tool.'],
      ['Can clients pay online through it?', 'Invoices carry your payment/bank instructions and share links, but there\'s no built-in card processing. Add your Stripe/PayPal link in the payment instructions.'],
      ['Do invoice emails come from my address?', 'Yes — bring your own SMTP (Gmail app password, Mailgun, Postmark…). Unlike FreshBooks, mail goes out from your own sender.'],
      ['Desktop or server?', 'Both — same code, same SQLite schema. Desktop app for offline invoicing; deploy to a $5 VPS when clients need to open share links from anywhere.'],
    ],
  },
  {
    slug: 'bookslot', brand: 'Bookslot', repo: 'booking-page', price: 39, icon: '📅',
    tagline: 'Your booking page. Your domain. No monthly fee.',
    oneliner: 'The Calendly you actually own — timezone-correct booking with email + ICS invites.',
    competitor: 'Calendly', compPrice: '$10/user/mo', compYr: 120,
    heroLead: 'Coaches, consultants, barbers, freelancers: stop renting your booking link for $10/month. Bookslot is a self-hosted scheduling app — visitors pick a time in their own timezone, get a confirmation email with a calendar invite, and you manage everything from a password-protected admin panel.',
    features: [
      ['📋', 'Event types', 'Name, duration, description, color, buffers, minimum notice, max days ahead — each with its own public link.'],
      ['🗓️', 'Weekly availability editor', 'Per-day time ranges in your timezone, plus one-off blocked dates and times.'],
      ['🌍', 'Timezone-correct slot math', 'Stored in UTC, computed in your timezone (DST-safe, unit-tested), displayed in the visitor\'s.'],
      ['🛡️', 'Double-booking protection', 'Slot validity re-checked inside a SQLite transaction at booking time.'],
      ['✉️', 'Email + ICS invites', 'Confirmation with calendar attachment to the visitor, notification to you — via your own SMTP.'],
      ['🔁', 'Cancel / reschedule links', 'Every confirmation includes a private tokenized link for the visitor.'],
      ['🖤', 'Clean dark booking page', 'Month calendar → slot picker → confirmation, with automatic timezone detection.'],
      ['🔒', '100% local & private', 'SQLite storage, no telemetry, no accounts, no external services.'],
    ],
    compRows: [
      ['Price', '$39 once', '$10/user/month, forever'],
      ['Cost after 3 years', '$39', '$360'],
      ['Your own domain', 'Yes', 'Their domain (branding is a paid add-on)'],
      ['Data ownership', 'SQLite file on your server', 'Their cloud'],
      ['Buffers, min notice, date limits', 'Yes', 'Yes'],
      ['Email + ICS invites', 'Yes (BYO SMTP)', 'Yes'],
      ['Cancel/reschedule links', 'Yes', 'Yes'],
      ['Telemetry / tracking', 'None', 'Their ToS'],
    ],
    payback: 'Pays for itself in under 4 months vs Calendly — then your booking link is free for life.',
    steps: [
      ['Buy once on Whop', 'One-time $39 for the packaged installer + priority support.'],
      ['Set your availability', 'Event types, weekly hours, buffers and blocked dates from the admin panel.'],
      ['Share your link', 'Visitors book in their own timezone and get an email with a calendar invite. You get notified.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/booking-page. $39 buys the packaged installer, 1-click setup, updates and priority support.'],
      ['Does it sync with Google Calendar?', 'Not two-way — that\'s Calendly\'s strongest feature and we\'ll say so. Bookslot sends .ics invites your calendar ingests, and you block busy times manually. If you live across 3 synced calendars, Calendly earns its fee.'],
      ['Do I need a server?', 'For a public booking page, yes — a $5 VPS with the included Docker setup. Desktop mode works for managing availability and bookings locally.'],
      ['Is the timezone handling actually correct?', 'Yes — bookings are stored in UTC, availability is computed DST-safely in your timezone, displayed in the visitor\'s, and the math is unit-tested including DST gap days.'],
      ['Can visitors cancel or reschedule?', 'Yes — every confirmation email includes a private tokenized cancel/reschedule link.'],
    ],
  },
  {
    slug: 'formforge', brand: 'Formforge', repo: 'form-builder', price: 39, icon: '📝',
    tagline: 'Self-hosted form builder + submissions inbox. No response caps.',
    oneliner: 'Typeform-style forms with unlimited responses, file uploads and CSV export — self-hosted.',
    competitor: 'Typeform', compPrice: '$29/mo', compYr: 348,
    heroLead: 'Build beautiful one-question-per-screen forms (or classic single-page forms), share a link or embed them anywhere, and collect unlimited responses into your own inbox — on your own server, with your own database. Typeform wants $348/yr and caps your responses.',
    features: [
      ['🧱', 'Drag-orderable field editor', '10 field types: short/long text, email, number, dropdown, radio, checkboxes, date, file upload, star rating.'],
      ['🎬', 'Two display modes', 'One-question-per-screen "Typeform-style" flow with keyboard navigation, or classic single page.'],
      ['🎛️', 'Form settings', 'Title, description, button text, success message or redirect URL, accent color, open/closed toggle.'],
      ['📥', 'Submissions inbox', 'Table view, detail drawer, one-click CSV export, downloadable file answers.'],
      ['📎', 'File uploads', 'Stored locally with size and type limits. Respondent files never touch a third party.'],
      ['🛡️', 'Spam protection', 'Honeypot field + per-IP rate limiting, client and server validation.'],
      ['✉️', 'Email notifications', 'Bring your own SMTP, get an email per submission.'],
      ['🔒', '100% local', 'SQLite database, local file storage, zero telemetry, zero external calls.'],
    ],
    compRows: [
      ['Price', '$39 one-time', '$29/mo ($348/yr)'],
      ['Responses', 'Unlimited', '100/mo (Basic)'],
      ['Forms', 'Unlimited', 'Capped by plan'],
      ['File uploads', 'Included, your disk', 'Higher tiers only'],
      ['Data ownership', 'Your server, your SQLite file', 'Their cloud'],
      ['One-question-per-screen UX', 'Yes', 'Yes'],
      ['CSV export', 'Yes', 'Yes'],
      ['Works offline / air-gapped', 'Yes', 'No'],
    ],
    payback: 'Six weeks of Typeform costs more than Formforge does once.',
    steps: [
      ['Buy once on Whop', 'One-time $39 for the packaged one-click installer, plus updates and setup support.'],
      ['Build your form', 'Drag fields into order, pick single-page or one-question-per-screen, set your accent color.'],
      ['Share or embed', 'Send /f/your-slug or copy the iframe snippet. Responses land in your inbox — unlimited, exportable to CSV.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/form-builder. $39 buys the packaged installer, 1-click setup, updates and setup support.'],
      ['Does it have logic jumps?', 'Not yet — fields are linear. Typeform\'s conditional logic and calculator are genuinely more advanced; if your forms branch heavily, Typeform still earns its price.'],
      ['Are responses really unlimited?', 'Yes — they\'re rows in your own SQLite file. The only limit is your disk.'],
      ['Do respondents\' files stay private?', 'Yes — uploads are stored on your own server/disk with size and type limits, and never touch a third party.'],
      ['Can I embed forms on my site?', 'Yes — copy-paste iframe snippet from the Share tab, or link straight to /f/your-slug.'],
    ],
  },
];
