/* Product data for the /software section — facts sourced from each repo's README */
module.exports = [
  {
    slug: 'pdfsmith', brand: 'PDFsmith', repo: 'pdf-toolkit', price: 29, icon: '📄',
    tagline: 'Every PDF tool you actually use — running 100% on your machine.',
    oneliner: 'Merge, split, rotate, watermark & convert PDFs offline. No uploads, ever.',
    competitor: 'SmallPDF', compPrice: '$12–15/mo', compYr: 144,
    heroLead: 'SmallPDF charges up to $15/month, forever, to do things your computer can do for free — and it uploads your documents to their servers to do it. PDFsmith does the same jobs locally, offline, with zero telemetry, for a one-time $29.',
    features: [
      ['🔗', 'Merge PDFs', 'Drag-drop any number of PDFs, reorder them in the list, combine into one file.'],
      ['✂️', 'Split PDF', 'Extract any page ranges (1-2 | 3 | 4-6) into separate new PDFs.'],
      ['🔄', 'Rotate pages', '90° / 180° / 270°, all pages or a specific range, batched across files.'],
      ['💧', 'Watermark', 'Text (position, size, opacity, diagonal) or image stamp — batch across files.'],
      ['🖼️', 'Images → PDF', 'JPG/PNG to PDF, one image per page, reorderable, A4-fit or native size.'],
      ['🏷️', 'Metadata editor', 'Read and rewrite title, author and subject — something SmallPDF doesn\'t even offer.'],
      ['🔒', '100% offline', 'All processing happens locally with pdf-lib. No network calls, no uploads, no account.'],
      ['🧾', 'No telemetry', 'Your contracts, invoices and records never leave your disk. Zero analytics.'],
    ],
    compRows: [
      ['Price', '$29 once', '$12–15/month ($144+/yr, forever)'],
      ['Your files', 'Never leave your machine', 'Uploaded to their servers'],
      ['Works offline', 'Yes', 'No'],
      ['Account required', 'No', 'Yes'],
      ['Merge / split / rotate', 'Yes', 'Yes'],
      ['Watermark (text + image)', 'Yes', 'Pro only'],
      ['Metadata editor', 'Yes', 'No'],
      ['Source code', 'MIT, on GitHub', 'Closed'],
    ],
    payback: 'Two and a half months of SmallPDF pays for PDFsmith outright. Everything after that is money you keep.',
    steps: [
      ['Buy once on Whop', 'One-time $29. You get the signed Windows installer — no account with us, no subscription to remember to cancel.'],
      ['Install in one click', 'Run the installer. No Node, no terminal, no setup. The app opens straight to the tools.'],
      ['Drop in your PDFs', 'Merge, split, rotate, watermark or convert — everything happens on your machine, instantly, offline.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes. The full source code is MIT-licensed at github.com/bensblueprints/pdf-toolkit and always will be. Buying gets you the signed Windows installer, 1-click setup and updates — pure convenience, zero lock-in.'],
      ['Do my PDFs get uploaded anywhere?', 'No. All processing runs locally with pdf-lib, a pure-JavaScript library. The app makes no network calls at all — you can run it with Wi-Fi off.'],
      ['What platforms does it run on?', 'The packaged installer is for Windows. The MIT source runs anywhere Electron does (Windows, macOS, Linux) if you build it yourself with Node 18+.'],
      ['Can it edit text inside a PDF?', 'No — and we\'d rather tell you that upfront. PDFsmith covers merge, split, rotate, watermark, images-to-PDF and metadata. For rewriting body text inside an existing PDF you still need a full editor like Acrobat.'],
      ['Is this a subscription in disguise?', 'No. $29 once. No renewal, no license server phoning home, no "lifetime deal" fine print. The app keeps working forever, even offline.'],
    ],
  },
  {
    slug: 'cutaway', brand: 'Cutaway', repo: 'bg-remover', price: 24, icon: '🪄',
    tagline: 'Remove image backgrounds with local AI. Unlimited images, full resolution, zero uploads.',
    oneliner: 'Local AI background removal — unlimited images, full resolution, nothing uploaded.',
    competitor: 'remove.bg', compPrice: '$9/mo (40 credits)', compYr: 108,
    heroLead: 'remove.bg charges $9/month for 40 credits — and every photo you upload goes to their servers. Cutaway runs the same class of AI model on your own machine: no credits, no upload, no monthly bill, no resolution cap.',
    features: [
      ['🖱️', 'Drag & drop batches', 'Single images or whole folders — JPG, PNG and WebP.'],
      ['👁️', 'Before / after preview', 'Checkerboard view of the transparent result, per image.'],
      ['🎨', 'Flexible output', 'Transparent PNG, white/black, or any custom background color.'],
      ['📦', 'Batch export', 'Pick a folder, hit one button, watch the progress bar.'],
      ['🔍', 'Full resolution, always', 'Your 6000×4000 photo stays 6000×4000. remove.bg\'s free tier caps at 0.25 MP.'],
      ['🔒', '100% private', 'The AI model (ONNX, U²-Net family) runs locally. Images never leave your computer.'],
      ['🧠', 'One-time model download', 'The ~80 MB AI model downloads once on first use — then everything works fully offline.'],
      ['🛡️', 'Memory-safe queue', 'Images process sequentially in an isolated worker, so a 40-image batch never freezes the UI.'],
    ],
    compRows: [
      ['Price', '$24 once', '$9/mo (40 credits) — $108/yr'],
      ['Images', 'Unlimited', '40/month, then buy credits'],
      ['Resolution', 'Full, always', 'Full res costs 1 credit per image'],
      ['Privacy', '100% local — nothing uploaded', 'Every image uploaded to their servers'],
      ['Offline', 'Yes (after one-time model download)', 'No'],
      ['Batch processing', 'Yes, built in', 'Paid API / desktop app with credits'],
      ['Source code', 'Open (MIT)', 'Closed'],
    ],
    payback: '$24 pays for itself in under 3 months — then it\'s free forever.',
    steps: [
      ['Buy once on Whop', 'One-time $24 gets you the packaged Windows installer with 1-click setup and updates.'],
      ['First run downloads the AI', 'The ~80 MB model downloads once, clearly shown in the UI. After that Cutaway is fully offline.'],
      ['Drop images, export cutouts', 'Batch a whole product shoot, preview each result, export transparent PNGs to any folder.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — the full source is MIT at github.com/bensblueprints/bg-remover. Paying $24 gets you the signed installer, 1-click setup and updates instead of building from source.'],
      ['Is the quality as good as remove.bg?', 'It uses the same class of segmentation model (U²-Net family via ONNX). On typical product shots and portraits results are comparable; on very fine edges like wispy hair, remove.bg\'s newest cloud models can still win. You get unlimited retries for free, though.'],
      ['Do my photos get uploaded?', 'Never. Inference runs on your CPU via onnxruntime. The only network call the app ever makes is the one-time model download.'],
      ['Is it fast?', 'It runs on your own hardware, one image at a time by design (predictable memory). A batch takes a few seconds per image on a modern CPU — no queue, no credits, no per-image anxiety.'],
      ['What formats are supported?', 'JPG, PNG and WebP in; transparent PNG or flat-color composites out, at the original resolution.'],
    ],
  },
  {
    slug: 'whisperdesk', brand: 'WhisperDesk', repo: 'whisper-transcriber', price: 39, icon: '🎙️',
    tagline: 'Unlimited local audio & video transcription. Your audio never leaves your machine.',
    oneliner: 'Whisper-powered transcription on your own CPU — unlimited minutes, TXT/SRT/VTT export.',
    competitor: 'Otter.ai', compPrice: '$16.99/mo', compYr: 204,
    heroLead: 'WhisperDesk does what Otter.ai charges $16.99/month for — but 100% locally, powered by whisper.cpp (OpenAI\'s Whisper model running natively on your CPU). Drop in any audio or video file, get back an accurate, timestamped transcript. No upload, no account, no per-minute limits.',
    features: [
      ['🎧', 'Drag & drop anything', 'mp3, wav, m4a, mp4, mov, mkv, flac, ogg, webm — video audio is extracted automatically.'],
      ['🔒', '100% private', 'Transcription runs entirely on your machine. Nothing is ever uploaded.'],
      ['♾️', 'Unlimited minutes', 'No cap, no monthly quota. Transcribe 10 hours a day if you want.'],
      ['🧠', 'Model picker', 'Tiny / base / small / medium, English-only or multilingual — downloaded once from Hugging Face.'],
      ['🌍', 'Language auto-detect', 'Or force English. Multilingual models cover dozens of languages.'],
      ['📊', 'Live progress', 'Real-time percentage while Whisper works, with timestamped transcript view and one-click copy.'],
      ['💾', 'Export TXT, SRT, VTT', 'Ready for subtitles, notes, or your editor.'],
      ['🕘', 'Local history', 'Every transcription saved locally — reload it any time.'],
    ],
    compRows: [
      ['Price', '$39 one-time', '$16.99/month, forever'],
      ['Cost after 1 year', '$39', '~$204'],
      ['Transcription limit', 'Unlimited', '1,200 min/mo (Pro)'],
      ['Max file length', 'Unlimited', '90 min per conversation'],
      ['Privacy', 'Audio never leaves your PC', 'Uploaded to their cloud'],
      ['Works offline', 'Yes', 'No'],
      ['Video files', 'Yes (audio auto-extracted)', 'Limited'],
      ['SRT/VTT subtitle export', 'Yes', 'Paid tiers'],
    ],
    payback: 'Pays for itself in under 3 months of Otter.ai Pro.',
    steps: [
      ['Buy once on Whop', 'One-time $39 for the packaged Windows installer — no terminal, no build step.'],
      ['Pick a model', 'On first run WhisperDesk fetches whisper.cpp (~8 MB) and your chosen model (78–148+ MB) with a visible progress bar. One time only.'],
      ['Drop a file, get a transcript', 'Timestamped text in minutes, exportable as TXT, SRT or VTT — all offline.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT-licensed at github.com/bensblueprints/whisper-transcriber, and it always will be. The $39 buys the signed installer, 1-click setup and updates.'],
      ['How accurate is it?', 'It runs OpenAI\'s Whisper models — the same family behind most modern transcription tools. Bigger models (small/medium) are more accurate and slower; you pick the trade-off.'],
      ['Does it do live meeting transcription?', 'No — and Otter is genuinely better for that. WhisperDesk transcribes files (recordings, interviews, videos, podcasts). If you need a live meeting assistant with speaker chat, keep Otter.'],
      ['How fast is it?', 'Depends on your CPU and model size. The tiny/base models typically run faster than real time on a modern machine; medium trades speed for accuracy.'],
      ['Does it need the internet?', 'Only twice, ever: the one-time whisper.cpp binary download and your chosen model from Hugging Face. After that it\'s fully offline.'],
    ],
  },
  {
    slug: 'shrinkray', brand: 'Shrinkray', repo: 'image-compressor', price: 19, icon: '🗜️',
    tagline: 'Unlimited local batch image compression & conversion.',
    oneliner: 'Batch-compress a thousand photos locally — JPG, PNG, WebP, AVIF — no upload limits.',
    competitor: 'TinyPNG Pro', compPrice: '~$39/yr + API fees', compYr: 39,
    heroLead: 'Stop uploading your images to random websites 20 at a time. Shrinkray runs 100% on your machine — drag in a thousand photos, pick a quality, and watch the megabytes melt away. No upload limits, no monthly bill, no cloud, no telemetry.',
    features: [
      ['🖼️', 'Drag & drop batches', 'JPG, PNG, WebP, AVIF, TIFF. Drop a whole shoot at once.'],
      ['📉', 'Live savings dashboard', 'Per-file and total before → after sizes with animated counters and % saved.'],
      ['🎚️', 'Quality slider', 'Full 1–100 control, powered by mozjpeg-grade encoders via sharp (libvips).'],
      ['🔁', 'Format conversion', 'Keep the original format, or convert everything to JPG, PNG, WebP or AVIF in one pass.'],
      ['📐', 'Max-dimension resize', 'Cap the longest edge for web exports — without upscaling.'],
      ['📁', 'Flexible output', 'Write to a chosen folder or alongside originals with a _compressed suffix. Originals are never touched.'],
      ['💾', 'Settings persist', 'Quality, format and output preferences remembered between sessions.'],
      ['🔒', '100% local', 'Zero network calls. Client photos and product shots never leave your disk.'],
    ],
    compRows: [
      ['Price', '$19 once', 'Subscription + per-image API fees at volume'],
      ['Upload limits', 'None — it\'s your CPU', 'Capped per month / per file size'],
      ['Max file size', 'Whatever your RAM handles', '75 MB cap'],
      ['Batch size', 'Unlimited', 'Limited per batch'],
      ['Formats', 'JPG, PNG, WebP, AVIF, TIFF', 'JPG, PNG, WebP, AVIF'],
      ['Privacy', 'Images never leave your machine', 'Every image uploaded to their servers'],
      ['Works offline', 'Yes', 'No'],
      ['Open source', 'Yes (MIT)', 'No'],
    ],
    payback: 'Pay for a few months of any subscription compressor and you\'ve already spent more than Shrinkray costs — and you still won\'t own anything.',
    steps: [
      ['Buy once on Whop', 'One-time $19 — the cheapest app in the suite, and probably the one you\'ll use most.'],
      ['Install in one click', 'Signed Windows installer. sharp ships prebuilt — nothing to compile, nothing to configure.'],
      ['Drop a folder, export', 'Set quality and format once; settings persist. Watch the savings counter climb.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/image-compressor. $19 gets you the signed installer, 1-click setup and updates.'],
      ['Is the compression as good as TinyPNG?', 'It uses sharp/libvips with mozjpeg-grade encoders — the same engines behind most professional pipelines. At equal quality settings, results are comparable; you also get AVIF, which typically beats PNG/JPG sizes outright.'],
      ['Will it overwrite my originals?', 'Never. Output goes to a folder you choose, or next to originals with a _compressed suffix.'],
      ['Is there an API or CLI?', 'Not in the app — it\'s a desktop tool. The MIT source exposes the pure-Node compression pipeline if you want to script it.'],
      ['Does it phone home?', 'No. Zero network calls, zero telemetry, no account. You can verify that in the source.'],
    ],
  },
  {
    slug: 'clipdeck', brand: 'ClipDeck', repo: 'screen-recorder-desktop', price: 29, icon: '🎥',
    tagline: 'The Loom replacement you buy once. Record, trim, export MP4 or GIF — all local.',
    oneliner: 'Screen + mic recording with local library, MP4 & two-pass GIF export. No cloud.',
    competitor: 'Loom', compPrice: '$15/mo', compYr: 180,
    heroLead: 'Record your screen and mic, save everything locally, export MP4 or GIF — no cloud, no monthly bill, no watermark, no upload limits. Your recordings live on your disk, not on someone else\'s server.',
    features: [
      ['🖥️', 'Source picker with live previews', 'Record any screen or individual window — thumbnails included.'],
      ['🎤', 'Microphone audio', 'One toggle, mixed cleanly with system audio into a single track.'],
      ['⏺️', 'Floating recording pill', 'Tiny always-on-top timer with a stop button, so the main window stays out of the shot.'],
      ['📚', 'Local library', 'Every recording auto-saves to Videos/Screen Recorder with thumbnails, and plays right in the app.'],
      ['🎬', 'MP4 export', 'H.264 + faststart — plays everywhere, with live progress.'],
      ['🌀', 'Optimized GIF export', 'Proper two-pass palette generation, not the muddy single-pass junk.'],
      ['✂️', 'Trim', 'Set start/end before exporting — no separate editor needed.'],
      ['🔒', '100% local', 'Zero telemetry, zero network calls, zero accounts, zero watermarks.'],
    ],
    compRows: [
      ['Price', '$29 once', '$15/mo, forever ($180/yr)'],
      ['Where videos live', 'Your disk', 'Their servers'],
      ['Recording length', 'Unlimited', 'Limited by plan'],
      ['Watermark', 'Never', 'On free tier'],
      ['Works offline', 'Yes', 'No'],
      ['Account required', 'No', 'Yes'],
      ['MP4 + GIF export', 'Built in', 'GIF gated by plan'],
      ['Your data mined for AI', 'Impossible — it never leaves', 'Read the ToS'],
    ],
    payback: 'Loom Business is $180/yr. ClipDeck is $29 once — it pays for itself in under 2 months.',
    steps: [
      ['Buy once on Whop', 'One-time $29 for the packaged installer, free updates forever.'],
      ['Pick a screen or window', 'Live-preview source picker, mic toggle, hit record. A floating pill keeps the timer out of your shot.'],
      ['Trim & export', 'MP4 for sharing anywhere, or a properly-paletted GIF for docs and PRs. Files stay in your Videos folder.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/screen-recorder-desktop. $29 buys the signed installer, 1-click setup and updates.'],
      ['Does it upload my videos anywhere?', 'No. There is no cloud. Recordings save to your Videos folder and never leave it unless you share them yourself.'],
      ['Can I share a link like Loom?', 'Not built in — that\'s the honest trade-off. Loom\'s instant share-link is its killer feature. ClipDeck gives you the file; share it via Drive, Slack or your own hosting.'],
      ['Does it record webcam?', 'It records screen or window plus microphone. A webcam overlay isn\'t in the current feature set — if that\'s essential, Loom or OBS may fit better.'],
      ['What about recording length limits?', 'None. Record until your disk is full.'],
    ],
  },
  {
    slug: 'upwatch', brand: 'Upwatch', repo: 'uptime-monitor', price: 39, icon: '📡',
    tagline: 'Self-hosted uptime monitoring + a beautiful public status page.',
    oneliner: 'HTTP checks, incident log, alerts and a branded 90-day status page — on your own box.',
    competitor: 'UptimeRobot', compPrice: '$8/mo', compYr: 96,
    heroLead: 'UptimeRobot charges $8/mo. Pingdom starts at $10/mo. Both cap your monitors and keep billing you forever. Upwatch is the same core product — HTTP checks, incident tracking, alerting, a classic 90-day-bar status page — running on your own $5 VPS (or your desktop) with unlimited monitors and zero recurring fees.',
    features: [
      ['🌐', 'HTTP(S) monitors', 'URL, interval from 30s to 15m, expected status code, optional keyword match.'],
      ['⚙️', 'In-process checker loop', 'No cron, no workers, no Redis — one Node process does everything.'],
      ['🗄️', 'SQLite storage', 'Check history with automatic 90-day retention pruning. One file to back up.'],
      ['📈', 'Per-monitor detail', 'Uptime % for 24h / 7d / 30d, response-time sparkline, full incident log.'],
      ['🟢', 'Public status page', 'Clean branded page at /status — per-monitor badges, classic 90-day uptime bars, outage banner.'],
      ['🔔', 'Alerts on down + recovery', 'Slack/Discord-compatible JSON webhook and email via your own SMTP.'],
      ['🏢', 'Built for agencies', 'Monitor every client site from one box; hand clients a clean branded status page.'],
      ['🖥️', 'Desktop or VPS', 'Run it as a desktop app, or deploy to a $5 VPS (Docker included) when it needs to be public.'],
    ],
    compRows: [
      ['Price', '$39 once', 'UptimeRobot $8/mo ($96/yr) · Pingdom $10+/mo'],
      ['Monitors', 'Unlimited', '50 on UptimeRobot\'s paid tier'],
      ['Check interval', '30s', '60s (paid)'],
      ['Public status page', 'Included, branded', 'Limited / upsell'],
      ['Keyword checks', 'Included', 'Paid tier'],
      ['Your data', 'Your SQLite file on your box', 'Their cloud'],
      ['Multi-client agency use', 'One VPS monitors everything', 'Per-account limits / pricing'],
    ],
    payback: 'Pays for itself vs UptimeRobot in under 5 months — then it\'s free forever.',
    steps: [
      ['Buy once on Whop', 'One-time $39 for the packaged, zero-config version with updates and priority support.'],
      ['Run it anywhere', 'Desktop app for personal use, or docker compose up on a $5 VPS for a public status page.'],
      ['Add monitors, get alerts', 'HTTP checks every 30s, webhook/email pings the second something breaks — and again when it recovers.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/uptime-monitor, always. The paid version is pure convenience: packaged installer, updates, priority support.'],
      ['Do I need a server?', 'Not necessarily. Desktop mode runs the whole app in an Electron window. For a public status page or 24/7 monitoring you\'ll want a $5 VPS — which is still cheaper per year than one month of most competitors\' higher tiers.'],
      ['What check types are supported?', 'HTTP(S) with status-code and keyword assertions. No ping/port/DNS checks yet — if you need those today, UptimeRobot still has the broader check menu.'],
      ['Where does monitoring run from?', 'From wherever you host it — one location. Cloud services check from multiple regions; that\'s their genuine advantage. For "is my site up and is checkout on the page", one good vantage point covers it.'],
      ['How do alerts work?', 'JSON webhooks (Slack/Discord-compatible) plus email through your own SMTP credentials, on both down and recovery.'],
    ],
  },
  {
    slug: 'trimly', brand: 'Trimly', repo: 'link-shortener', price: 29, icon: '🔗',
    tagline: 'Your own branded link shortener with full click analytics.',
    oneliner: 'Branded short links, QR codes and click analytics — on your domain, in your SQLite file.',
    competitor: 'Bitly', compPrice: '$29/mo', compYr: 348,
    heroLead: 'Bitly charges $348/year just to use your own domain with your links — and your click data lives on their servers. Trimly runs on your $5 VPS (or right on your desktop), keeps every click in a local SQLite file you own, and never phones home.',
    features: [
      ['🏷️', 'Branded short links', 'Auto-generated or custom slugs on your own domain.'],
      ['📊', 'Click analytics', 'Total + unique clicks, clicks-over-time chart, top referrers, devices, browsers, countries.'],
      ['🔲', 'QR code for every link', 'Downloadable PNG and SVG.'],
      ['↪️', '301 / 302 per link', 'SEO-permanent or trackable-temporary — your call, editable any time.'],
      ['🧰', 'UTM builder', 'Built into the create form — tag campaigns without a spreadsheet.'],
      ['📥', 'Bulk CSV import & export', 'Migrate off Bitly in one paste.'],
      ['🌍', 'Country detection, zero paid APIs', 'Reads CF-IPCountry behind free Cloudflare; degrades gracefully otherwise.'],
      ['🔒', '100% local & private', 'SQLite storage, no telemetry, no tracking pixels, no external calls.'],
    ],
    compRows: [
      ['Price', '$29 once', '$29/mo ($348/yr) for a custom domain'],
      ['Your own domain', 'Included', 'Paid plans only'],
      ['Links', 'Unlimited', 'Capped per plan'],
      ['Click data ownership', 'Your SQLite file', 'Their servers'],
      ['QR codes (PNG + SVG)', 'Included', 'Limited / paid tiers'],
      ['Bulk CSV import/export', 'Yes', 'Paid tiers'],
      ['Tracking pixels / telemetry', 'None', 'Their business model'],
    ],
    payback: 'One month of Bitly\'s custom-domain plan costs the same as Trimly does once.',
    steps: [
      ['Buy once on Whop', 'One-time $29 — installer, updates and setup support included.'],
      ['Point your domain', 'Deploy to a $5 VPS with Docker, point go.yourbrand.com at it, put free Cloudflare in front for country analytics.'],
      ['Create links, watch clicks', 'Custom slugs, UTM builder, QR codes, and a full analytics dashboard you own.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/link-shortener. The $29 buys the packaged 1-click installer, updates and setup support.'],
      ['Do I need a server for public links?', 'Yes — public short links need a public host, so budget a $5/mo VPS. Desktop mode works fully offline for QR generation and campaign planning. Even VPS + Trimly year one costs less than 3 months of Bitly.'],
      ['Can I migrate from Bitly?', 'Yes — bulk CSV import is built in. Export from Bitly, paste, done. Printed QR codes keep working because destinations stay editable.'],
      ['How accurate is the geo data?', 'Country detection reads Cloudflare\'s free CF-IPCountry header — no paid geo API. Without Cloudflare in front, country data degrades gracefully to unknown.'],
      ['Is there click fraud / bot filtering?', 'Uniques use a privacy-friendly daily IP+UA hash, which de-dupes repeat visitors. There\'s no enterprise-grade bot scoring — Bitly\'s bigger plans do more there.'],
    ],
  },
  {
    slug: 'billcraft', brand: 'Billcraft', repo: 'invoice-generator', price: 39, icon: '🧾',
    tagline: 'Self-hosted invoicing for freelancers and small businesses.',
    oneliner: 'Clients, invoices, PDFs, share links & recurring billing — on hardware you control.',
    competitor: 'FreshBooks', compPrice: '$19/mo', compYr: 228,
    heroLead: 'FreshBooks charges $19/month, forever, to store your client list and send your invoices from their servers. Billcraft is the same core workflow — clients, invoices, PDFs, shareable payment links, recurring billing — running entirely on your machine (or your $5 VPS).',
    features: [
      ['🏢', 'Business profile', 'Name, logo, address, tax ID, currency and payment/bank instructions printed on every invoice.'],
      ['👥', 'Unlimited clients', 'Full CRUD with company, email, address, notes. FreshBooks Lite caps you at 5 billable clients.'],
      ['🧾', 'Real invoices', 'Line items (qty × rate), tax %, discount %, notes, due dates, configurable numbering.'],
      ['📄', 'Professional PDFs', 'Clean server-side template (pdfkit — no headless browser) with your logo and status pill.'],
      ['🔗', 'Public share links', 'Clients open /inv/<token>, see a polished invoice page, download the PDF — no login.'],
      ['📊', 'Dashboard', 'Outstanding total, paid this month, overdue list at a glance — overdue computed automatically.'],
      ['🔁', 'Recurring invoices', 'Monthly templates auto-create drafts; optionally auto-email them via your SMTP.'],
      ['🔒', '100% local', 'SQLite database, no telemetry, no external services. Your client data stays yours.'],
    ],
    compRows: [
      ['Price', '$39 once', '$19/month ($228/yr)'],
      ['Clients', 'Unlimited', '5 billable clients (Lite)'],
      ['Your data', 'On your machine/server', 'Their cloud'],
      ['Invoices + PDF + share links', 'Yes', 'Yes'],
      ['Recurring invoices', 'Yes', 'Yes'],
      ['Email via your own SMTP', 'Yes', 'No (their sender)'],
      ['Works offline (desktop mode)', 'Yes', 'No'],
      ['Source code', 'MIT, yours', 'Closed'],
    ],
    payback: 'Two months of FreshBooks pays for Billcraft outright. Everything after that is free, forever.',
    steps: [
      ['Buy once on Whop', 'One-time $39 for the packaged Windows installer — zero terminal time.'],
      ['Set up your business profile', 'Logo, tax ID, numbering, payment instructions — printed on every invoice automatically.'],
      ['Invoice and get paid', 'Send polished PDF invoices or share links; recurring templates handle your retainers.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/invoice-generator. $39 gets you the signed installer, 1-click setup and updates.'],
      ['Does it do accounting / bookkeeping?', 'No — and that matters. Billcraft is invoicing: clients, invoices, PDFs, recurring billing. FreshBooks also does expenses, time tracking and accounting reports. If you need double-entry books, keep an accounting tool.'],
      ['Can clients pay online through it?', 'Invoices carry your payment/bank instructions and share links, but there\'s no built-in card processing. Add your Stripe/PayPal link in the payment instructions.'],
      ['Do invoice emails come from my address?', 'Yes — bring your own SMTP (Gmail app password, Mailgun, Postmark…). Unlike FreshBooks, mail goes out from your own sender.'],
      ['Desktop or server?', 'Both — same code, same SQLite schema. Desktop app for offline invoicing; deploy to a $5 VPS when clients need to open share links from anywhere.'],
    ],
  },
  {
    slug: 'bookslot', brand: 'Bookslot', repo: 'booking-page', price: 39, icon: '📅',
    tagline: 'Your booking page. Your domain. No monthly fee.',
    oneliner: 'The Calendly you actually own — timezone-correct booking with email + ICS invites.',
    competitor: 'Calendly', compPrice: '$10/user/mo', compYr: 120,
    heroLead: 'Coaches, consultants, barbers, freelancers: stop renting your booking link for $10/month. Bookslot is a self-hosted scheduling app — visitors pick a time in their own timezone, get a confirmation email with a calendar invite, and you manage everything from a password-protected admin panel.',
    features: [
      ['📋', 'Event types', 'Name, duration, description, color, buffers, minimum notice, max days ahead — each with its own public link.'],
      ['🗓️', 'Weekly availability editor', 'Per-day time ranges in your timezone, plus one-off blocked dates and times.'],
      ['🌍', 'Timezone-correct slot math', 'Stored in UTC, computed in your timezone (DST-safe, unit-tested), displayed in the visitor\'s.'],
      ['🛡️', 'Double-booking protection', 'Slot validity re-checked inside a SQLite transaction at booking time.'],
      ['✉️', 'Email + ICS invites', 'Confirmation with calendar attachment to the visitor, notification to you — via your own SMTP.'],
      ['🔁', 'Cancel / reschedule links', 'Every confirmation includes a private tokenized link for the visitor.'],
      ['🖤', 'Clean dark booking page', 'Month calendar → slot picker → confirmation, with automatic timezone detection.'],
      ['🔒', '100% local & private', 'SQLite storage, no telemetry, no accounts, no external services.'],
    ],
    compRows: [
      ['Price', '$39 once', '$10/user/month, forever'],
      ['Cost after 3 years', '$39', '$360'],
      ['Your own domain', 'Yes', 'Their domain (branding is a paid add-on)'],
      ['Data ownership', 'SQLite file on your server', 'Their cloud'],
      ['Buffers, min notice, date limits', 'Yes', 'Yes'],
      ['Email + ICS invites', 'Yes (BYO SMTP)', 'Yes'],
      ['Cancel/reschedule links', 'Yes', 'Yes'],
      ['Telemetry / tracking', 'None', 'Their ToS'],
    ],
    payback: 'Pays for itself in under 4 months vs Calendly — then your booking link is free for life.',
    steps: [
      ['Buy once on Whop', 'One-time $39 for the packaged installer + priority support.'],
      ['Set your availability', 'Event types, weekly hours, buffers and blocked dates from the admin panel.'],
      ['Share your link', 'Visitors book in their own timezone and get an email with a calendar invite. You get notified.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/booking-page. $39 buys the packaged installer, 1-click setup, updates and priority support.'],
      ['Does it sync with Google Calendar?', 'Not two-way — that\'s Calendly\'s strongest feature and we\'ll say so. Bookslot sends .ics invites your calendar ingests, and you block busy times manually. If you live across 3 synced calendars, Calendly earns its fee.'],
      ['Do I need a server?', 'For a public booking page, yes — a $5 VPS with the included Docker setup. Desktop mode works for managing availability and bookings locally.'],
      ['Is the timezone handling actually correct?', 'Yes — bookings are stored in UTC, availability is computed DST-safely in your timezone, displayed in the visitor\'s, and the math is unit-tested including DST gap days.'],
      ['Can visitors cancel or reschedule?', 'Yes — every confirmation email includes a private tokenized cancel/reschedule link.'],
    ],
  },
  {
    slug: 'formforge', brand: 'Formforge', repo: 'form-builder', price: 39, icon: '📝',
    tagline: 'Self-hosted form builder + submissions inbox. No response caps.',
    oneliner: 'Typeform-style forms with unlimited responses, file uploads and CSV export — self-hosted.',
    competitor: 'Typeform', compPrice: '$29/mo', compYr: 348,
    heroLead: 'Build beautiful one-question-per-screen forms (or classic single-page forms), share a link or embed them anywhere, and collect unlimited responses into your own inbox — on your own server, with your own database. Typeform wants $348/yr and caps your responses.',
    features: [
      ['🧱', 'Drag-orderable field editor', '10 field types: short/long text, email, number, dropdown, radio, checkboxes, date, file upload, star rating.'],
      ['🎬', 'Two display modes', 'One-question-per-screen "Typeform-style" flow with keyboard navigation, or classic single page.'],
      ['🎛️', 'Form settings', 'Title, description, button text, success message or redirect URL, accent color, open/closed toggle.'],
      ['📥', 'Submissions inbox', 'Table view, detail drawer, one-click CSV export, downloadable file answers.'],
      ['📎', 'File uploads', 'Stored locally with size and type limits. Respondent files never touch a third party.'],
      ['🛡️', 'Spam protection', 'Honeypot field + per-IP rate limiting, client and server validation.'],
      ['✉️', 'Email notifications', 'Bring your own SMTP, get an email per submission.'],
      ['🔒', '100% local', 'SQLite database, local file storage, zero telemetry, zero external calls.'],
    ],
    compRows: [
      ['Price', '$39 one-time', '$29/mo ($348/yr)'],
      ['Responses', 'Unlimited', '100/mo (Basic)'],
      ['Forms', 'Unlimited', 'Capped by plan'],
      ['File uploads', 'Included, your disk', 'Higher tiers only'],
      ['Data ownership', 'Your server, your SQLite file', 'Their cloud'],
      ['One-question-per-screen UX', 'Yes', 'Yes'],
      ['CSV export', 'Yes', 'Yes'],
      ['Works offline / air-gapped', 'Yes', 'No'],
    ],
    payback: 'Six weeks of Typeform costs more than Formforge does once.',
    steps: [
      ['Buy once on Whop', 'One-time $39 for the packaged one-click installer, plus updates and setup support.'],
      ['Build your form', 'Drag fields into order, pick single-page or one-question-per-screen, set your accent color.'],
      ['Share or embed', 'Send /f/your-slug or copy the iframe snippet. Responses land in your inbox — unlimited, exportable to CSV.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/form-builder. $39 buys the packaged installer, 1-click setup, updates and setup support.'],
      ['Does it have logic jumps?', 'Not yet — fields are linear. Typeform\'s conditional logic and calculator are genuinely more advanced; if your forms branch heavily, Typeform still earns its price.'],
      ['Are responses really unlimited?', 'Yes — they\'re rows in your own SQLite file. The only limit is your disk.'],
      ['Do respondents\' files stay private?', 'Yes — uploads are stored on your own server/disk with size and type limits, and never touch a third party.'],
      ['Can I embed forms on my site?', 'Yes — copy-paste iframe snippet from the Share tab, or link straight to /f/your-slug.'],
    ],
  },
  {
    slug: 'sigcraft', brand: 'SigCraft', repo: 'email-signature', price: 15, icon: '✒️',
    tagline: 'Professional email signatures for your whole team — on your desktop, forever.',
    oneliner: 'Email-safe HTML signatures with 10 templates and team CSV batch export — 100% local.',
    competitor: 'WiseStamp', compPrice: '$6/mo/user', compYr: 72,
    heroLead: 'WiseStamp charges $6/month per user, forever, to generate what is at the end of the day a block of HTML — and the free tier stamps their ad into your signature. SigCraft does the same job locally, for every team member you\'ll ever have, with zero recurring cost and zero telemetry.',
    features: [
      ['🎨', '10 polished templates', 'Classic, Modern Sidebar, Minimal, Bold Accent Bar, Card, Compact, Corporate, Creative, Photo Left, Photo Top.'],
      ['📧', 'Email-safe HTML', 'Table layouts, 100% inline styles, Outlook (VML) conditional comments — renders correctly in Gmail, Outlook desktop & web, Apple Mail, Thunderbird.'],
      ['🖼️', 'Headshot / logo upload', 'Drag & drop, auto-resized and embedded as base64 — or use a hosted image URL for maximum client compatibility.'],
      ['🌐', '12 social networks', 'LinkedIn, X, Facebook, Instagram, YouTube, TikTok, GitHub and more — brand-colored or monochrome pure-HTML badges, no broken-image icons.'],
      ['🔘', 'Banner + CTA button', 'Optional promo banner with click-through link and a bulletproof colored CTA button.'],
      ['👁️', 'Live preview', 'Desktop/mobile width toggle, light/dark background toggle, with in-app install guides for every major client.'],
      ['👥', 'Team mode', 'Import a CSV of people, generate signatures for everyone with your chosen template, batch-export a folder of .html files.'],
      ['🔒', '100% local', 'No network calls, no telemetry, no account. Profiles autosave to local JSON.'],
    ],
    compRows: [
      ['Price', '$15 once', '$6/mo/user, forever'],
      ['1 user, 3 years', '$15', '$216'],
      ['5-person team, 3 years', '$15', '$1,080'],
      ['Their branding in your signature', 'Never', 'On free tier'],
      ['Works offline / air-gapped', 'Yes', 'No'],
      ['Team CSV batch generation', 'Included', 'Higher "Teams" tier'],
      ['Templates', '10', '~50'],
      ['Source code', 'MIT, yours', 'Closed'],
    ],
    payback: 'Three months of WiseStamp for one user costs more than SigCraft does for your whole team, forever.',
    steps: [
      ['Buy once on Whop', 'One-time $15 — the least expensive app in the suite. Signed installer, 1-click setup, updates included.'],
      ['Fill in your details', 'Name, title, phones, socials, headshot, CTA — watch the live preview update in desktop and mobile widths.'],
      ['Copy into your email client', 'One-click rich copy pastes straight into Gmail\'s signature box; step-by-step guides cover Outlook, Apple Mail and Thunderbird.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/email-signature. $15 buys the signed Windows installer, 1-click setup and updates.'],
      ['Will the signature render correctly in Outlook?', 'Yes — output uses table layouts, fully inline styles and VML conditional comments for the CTA button, the techniques email developers use for Outlook compatibility.'],
      ['Can I make signatures for my whole team?', 'Yes — team mode imports a CSV and batch-exports a folder of .html signatures with your chosen template. No per-user pricing, ever.'],
      ['Does it have as many templates as WiseStamp?', 'No — 10 versus roughly 50. We\'d rather ship 10 templates that render everywhere than 50 that break in Outlook. If you want maximum variety, WiseStamp wins there.'],
      ['Does it phone home or inject branding?', 'Never. No network calls, no telemetry, and nothing of ours in your signature — unlike WiseStamp\'s free tier, which stamps its ad into every email you send.'],
    ],
  },
  {
    slug: 'postdock', brand: 'PostDock', repo: 'social-scheduler', price: 49, icon: '📣',
    tagline: 'Schedule to X, Facebook, Instagram, LinkedIn and Mastodon from your own box — pay once.',
    oneliner: 'Self-hosted social scheduling — composer, queue, content recycling & webhooks. Your API keys, your data.',
    competitor: 'Buffer', compPrice: '$6/channel/mo', compYr: 360,
    heroLead: 'Buffer charges $6 per channel per month, forever — five channels is $360 a year, every year. PostDock is the same core workflow — compose, preview, schedule, queue, recycle — running on your machine or your $5 VPS, with your own API keys. Nobody can raise the price on you, throttle your channels, or hold your posting history hostage.',
    features: [
      ['🔌', '5 pluggable channels', 'X/Twitter, Facebook Page + Instagram Business, LinkedIn, Mastodon — all with your own API keys, every credential on your box.'],
      ['🪝', 'Webhook escape hatch', 'POSTs the content JSON to Zapier, Make, n8n or your own endpoint with optional HMAC-SHA256 signing — your route to every other network.'],
      ['✍️', 'Composer with live previews', 'Text + up to 4 images, per-network character counters (280/500/2200/3000) and preview cards per channel.'],
      ['🕑', 'Timezone-aware scheduling', 'Pick any IANA timezone; DST handled correctly. Post now or schedule.'],
      ['📆', 'Queue calendar', 'Month calendar and list view of everything scheduled — edit or delete before it goes out.'],
      ['🔁', 'Content recycling', 'Toggle "repost every N days" and evergreen content re-queues itself after each successful publish.'],
      ['🚨', 'Statuses that tell the truth', 'Scheduled → publishing → published / failed with the actual API error, plus a Retry button that only re-hits the channels that failed.'],
      ['🔒', '100% yours', 'SQLite on your disk, in-process 1-second scheduler (no Redis, no cron daemon), crash-safe recovery, zero telemetry.'],
    ],
    compRows: [
      ['Price', '$49 once', '$6/channel/month, forever'],
      ['5 channels, 3 years', '$49', '$1,080'],
      ['Channel limit', 'Unlimited', 'Pay per channel'],
      ['Scheduled posts', 'Unlimited', 'Capped on cheap tiers'],
      ['Your API keys & data', 'SQLite on your disk', 'Their cloud'],
      ['Content recycling', 'Built in', 'That\'s ReQueue/SmarterQueue — another $25/mo'],
      ['Webhook / Zapier escape hatch', 'Built in', 'Paid add-ons'],
      ['Source code', 'MIT, yours forever', 'Closed'],
    ],
    payback: 'Eight months of a single Buffer channel pays for PostDock outright — a five-channel setup pays it back in under two months.',
    steps: [
      ['Buy once on Whop', 'One-time $49 for the packaged Windows installer — no terminal, no build step, updates included.'],
      ['Connect your channels', 'Every driver has a step-by-step guide inside the app. Mastodon and webhooks take 2 minutes; X about 10; LinkedIn 15; Facebook + Instagram around 20.'],
      ['Compose, schedule, recycle', 'Per-network previews and counters, a timezone-aware queue, and evergreen recycling that keeps your best content circulating.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — the full source is MIT at github.com/bensblueprints/social-scheduler. $49 buys the signed installer, 1-click setup and updates — pure convenience, zero lock-in.'],
      ['Do I need my own API keys?', 'Yes — that\'s the point. Bring-your-own-keys means every credential stays on your box and nobody can throttle or re-price your channels. In-app guides walk you through each network: Mastodon and webhooks in 2 minutes, Meta in about 20.'],
      ['Does Instagram work from a desktop?', 'Instagram publishing needs a public URL because Meta\'s API downloads your images from it — so IG requires the $5 VPS mode with PUBLIC_BASE_URL set. Every other channel works fine from a desktop behind NAT.'],
      ['What about TikTok, Pinterest or Threads?', 'No native drivers yet — honestly. The webhook driver plus Zapier/Make/n8n covers them today, and drivers are pluggable (one file in server/channels/) if you build from source.'],
      ['Is this a subscription in disguise?', 'No. $49 once. No renewal, no license server phoning home, no per-channel meter. The app keeps working forever, even offline.'],
    ],
  },
  {
    slug: 'linkleaf', brand: 'Linkleaf', repo: 'link-in-bio', price: 19, icon: '🌿',
    tagline: 'Your link-in-bio page on your own domain. No branding, no rent.',
    oneliner: 'Self-hosted link-in-bio with themes, link scheduling, email capture & analytics — no monthly fee.',
    competitor: 'Linktree', compPrice: '$5–9/mo', compYr: 84,
    heroLead: 'Linktree charges $5–9/month to host what is, at heart, one small page — and stamps its own branding on the free tier. Linkleaf is that page on your own domain: 6 themes, drag-to-reorder blocks, link scheduling, email capture into your own database, and analytics nobody else can see or sell.',
    features: [
      ['👤', 'Full profile', 'Avatar upload, display name, bio and a social icon row covering 12 networks.'],
      ['🧱', 'Blocks', 'Links with optional thumbnails and hover animation, headers/dividers, embedded YouTube, and email-collect blocks.'],
      ['✋', 'Drag to reorder', 'Grab the grip, drop, done — order saves automatically.'],
      ['⏰', 'Link scheduling', 'Give any block a start/end date — launch-day links and limited drops handle themselves.'],
      ['🎨', '6 polished themes', 'Gradient, glass, minimal light, dark, neon, paper — plus custom accent color, custom background and a custom CSS box for full control.'],
      ['✉️', 'Email capture + CSV export', 'Subscribers land in your SQLite database with one-click CSV export. Your list is yours.'],
      ['📊', 'Analytics you own', 'Page views, clicks per link, CTR and a 30-day chart. Not sold to anyone.'],
      ['⚡', 'Fast, private public page', 'Server-rendered HTML with self-hosted fonts — the public page makes zero external requests. SEO meta + Open Graph included.'],
    ],
    compRows: [
      ['Price', '$19 once', '$5–9/mo, forever'],
      ['Your own domain', 'Yes, natively', 'Paid plan only'],
      ['Their branding on your page', 'None', 'On free plan'],
      ['Email capture + CSV export', 'Built in', 'Paid plan'],
      ['Link scheduling', 'Built in', 'Paid plan'],
      ['Analytics', 'Yours, in your SQLite', 'Theirs, on their servers'],
      ['Custom CSS', 'Yes', 'No'],
      ['Cost over 3 years', '$19', '$180–324'],
    ],
    payback: 'Three months of Linktree Pro costs more than Linkleaf does once — and you get your own domain from day one.',
    steps: [
      ['Buy once on Whop', 'One-time $19 — one of the cheapest apps in the suite. Signed installer, 1-click setup, updates included.'],
      ['Point your domain', 'Deploy to a $5 VPS with the included Docker setup, put Caddy or free Cloudflare in front — yourname.com is your link-in-bio. Or start in desktop mode.'],
      ['Add blocks, share the link', 'Drag to reorder, schedule launch links, collect emails into your own database, and watch analytics you own.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/link-in-bio, always. $19 buys the packaged installer, 1-click setup and updates.'],
      ['Do I need a server?', 'For a public page, yes — a $5 VPS with the included Docker setup. Even VPS + Linkleaf in year one costs about what Linktree charges, and after that the app itself is free forever. Desktop mode works for building and previewing your page.'],
      ['Can I migrate from Linktree?', 'There\'s no automatic importer — honestly. You re-add your links in the admin panel; most pages take under ten minutes to rebuild, and then you never pay rent on them again.'],
      ['Is the public page fast?', 'Yes — it\'s server-rendered plain HTML with self-hosted fonts and zero external requests. No framework payload, no Google Fonts ping, no trackers. It loads instantly on mobile.'],
      ['What happens to my page if Linkleaf disappears?', 'Nothing — it\'s running on your server from MIT-licensed source, with your data in one SQLite file and an uploads folder. Back up = copy two things.'],
    ],
  },
  {
    slug: 'scantrail', brand: 'Scantrail', repo: 'qr-tracker', price: 24, icon: '🔳',
    tagline: 'Dynamic QR codes you print once and re-point forever — with scan analytics you own.',
    oneliner: 'Self-hosted dynamic QR codes with scan analytics, a design studio and batch CSV generation.',
    competitor: 'QR Tiger', compPrice: '$15/mo', compYr: 180,
    heroLead: 'QR Tiger charges $15+/month — and if you stop paying, your printed codes die. Scantrail generates dynamic QR codes that route through your own domain, so you can swap the destination any time without reprinting a single menu, poster or business card. Every scan lands in a SQLite file you own.',
    features: [
      ['🔁', 'Dynamic codes', 'The QR encodes /q/your-slug on your domain and 302-redirects to an editable destination. Reprint nothing, ever.'],
      ['📊', 'Scan analytics', 'Total + unique scans, scans-over-time chart, device/OS/browser breakdown, country, hour-of-day heatstrip and a recent-scan log.'],
      ['🗂️', 'Every QR type you need', 'URL (dynamic + tracked), vCard (serves a .vcf download, also tracked), WiFi, plain text, email and phone.'],
      ['🎨', 'Design studio', 'Foreground/background colors, square / rounded / dots module styles, error-correction level, center logo upload, live preview.'],
      ['🖨️', 'Print-ready export', 'PNG at 512 / 1024 / 2048 / 4096 px and true vector SVG.'],
      ['📦', 'Batch CSV → zip', 'Paste or drop a name,destination CSV and get a zip of print-ready PNGs — every row a tracked dynamic code.'],
      ['🗃️', 'Folders & tags', 'Organize hundreds of codes per client, campaign or location.'],
      ['🔒', '100% local & private', 'SQLite on disk, no telemetry, no external services.'],
    ],
    compRows: [
      ['Price', '$24 once', '$15/month, forever'],
      ['Dynamic (editable) QR codes', 'Unlimited', 'Capped by plan'],
      ['Codes if you stop paying', 'Always work — you host them', 'Die with your plan'],
      ['Scan analytics', 'Included', 'Included'],
      ['Custom colors, dot styles, logo', 'Included', 'Included'],
      ['Batch CSV generation', 'Included', 'Higher tiers'],
      ['Redirect domain', 'Yours', 'Theirs (qrco.de)'],
      ['Scan data', 'Your SQLite file', 'Their cloud'],
    ],
    payback: 'Under two months of QR Tiger pays for Scantrail — and your printed codes can never be held hostage again.',
    steps: [
      ['Buy once on Whop', 'One-time $24 for the packaged Windows installer with 1-click setup and updates.'],
      ['Deploy where your codes will live', 'For printed, distributed codes, a $5 VPS with your domain and PUBLIC_URL set — that URL is what ends up inside the QR. Desktop mode covers design and testing.'],
      ['Print once, edit forever', 'Swap destinations any time without reprinting. Put free Cloudflare in front and country analytics light up automatically.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/qr-tracker. $24 buys the signed installer, 1-click setup and updates.'],
      ['Why do dynamic codes need a server?', 'Because the QR encodes a URL on your domain that redirects to the real destination — that\'s what makes it editable after printing. A $5 VPS covers it; desktop mode is fine for designing, testing and static codes.'],
      ['What happens to my codes if I stop using Scantrail?', 'Nothing — they point at your domain, not ours. As long as your server answers, every printed code keeps working. That\'s the whole difference from hosted services, where codes die with your plan.'],
      ['How does country tracking work?', 'It reads Cloudflare\'s free CF-IPCountry header — put free Cloudflare in front of your VPS and country analytics appear. Without it, country data degrades gracefully to unknown. No paid geo API.'],
      ['Is the QR output actually tested?', 'Yes — the smoke test decodes generated PNGs with jsQR (including rounded and dots styles with a center logo), hits the redirect, and asserts the scan rows and analytics land.'],
    ],
  },
  {
    slug: 'cardsmith', brand: 'Cardsmith', repo: 'og-image-studio', price: 39, icon: '🎴',
    tagline: 'Design social-card templates visually, render them from a GET request. Your self-hosted Bannerbear.',
    oneliner: 'Visual OG-image templates that become render APIs — unlimited PNGs, bulk CSV, self-hosted.',
    competitor: 'Bannerbear', compPrice: '$49/mo', compYr: 588,
    heroLead: 'Bannerbear charges $49/month — $588 a year — to render social cards from templates. Cardsmith is the same idea on your own hardware: design a template in the visual editor, type {{title}} in a text layer, and it instantly becomes a REST endpoint that returns a PNG. Unlimited renders, no rate limits, no meter.',
    features: [
      ['🎨', 'Visual template editor', 'Canvas with drag positioning + snap guides, layers panel, and a live preview that matches server output pixel-for-pixel.'],
      ['🧩', 'Layer types', 'Text (bundled fonts, weight, align, wrap, auto-shrink to fit), images (upload or URL, cover/contain/fill, radius, opacity), shapes and solid/gradient/image backgrounds.'],
      ['📐', 'Sizes for every network', 'OG/blog 1200×630, X large card 1600×900, Instagram 1080×1080 and 1080×1920 story, LinkedIn 1200×627 — plus fully custom dimensions.'],
      ['🔤', '{{variables}}', 'Type {{title}} in any text layer (or image URL) and the template instantly becomes an API endpoint with that parameter.'],
      ['⚙️', 'Render API', 'GET /api/render/:templateId?title=...&key=... returns a PNG — deterministic, server-side, bundled Chromium. Point your og:image meta tag straight at it.'],
      ['📦', 'Bulk CSV → zip', 'Upload a CSV, get one PNG per row (up to 500). Batch your podcast back-catalog in one request.'],
      ['🖼️', 'Gallery + starter templates', 'Every API render logged and browsable with its exact params; 5 polished starter templates included.'],
      ['🔒', '100% local', 'SQLite + filesystem, no telemetry. Your renders never touch a third party.'],
    ],
    compRows: [
      ['Price', '$39 once (or free, MIT)', '$49/month ($588/yr)'],
      ['API renders', 'Unlimited', '1,000/mo on Starter'],
      ['Templates', 'Unlimited', '10 on Starter'],
      ['Data location', 'Your machine / your VPS', 'Their cloud'],
      ['Rate limits', 'None', 'Yes'],
      ['Works offline', 'Yes', 'No'],
      ['Source code', 'MIT, yours', 'Closed'],
    ],
    payback: 'Cardsmith costs less than a single month of Bannerbear — it pays for itself in 24 days.',
    steps: [
      ['Buy once on Whop', 'One-time $39 for the packaged installer — Chromium and every render dependency pre-wired.'],
      ['Design a template', 'Drag layers on the canvas or start from one of 5 starter templates. Type {{title}} wherever dynamic text goes.'],
      ['Call the API', 'Drop the render URL into your og:image tag, script it from Node or serverless, or bulk-render a CSV into a zip of PNGs.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/og-image-studio. $39 buys the packaged installer with everything pre-wired, plus updates.'],
      ['How are images rendered?', 'Server-side with bundled Chromium (Puppeteer), using the exact same HTML renderer as the editor preview — so WYSIWYG is literal. Fonts are bundled and base64-embedded, making output deterministic and fully offline.'],
      ['Are renders really unlimited?', 'Yes — your CPU does the work, so there\'s no render meter and no rate limit. Bannerbear\'s Starter tier caps you at 1,000 renders and 10 templates a month.'],
      ['Can I use it for live og:image tags?', 'Yes — point your meta tags at the render URL (auth via ?key= or X-Api-Key); images render on demand and log to the gallery. For public traffic, host it on a $5 VPS with the included Docker setup.'],
      ['What\'s the honest catch vs Bannerbear?', 'Bannerbear has no-code integrations (Zapier, Airtable), video/GIF generation and managed infrastructure. Cardsmith is images only, on hardware you run. If you need those integrations without touching a server, Bannerbear earns its fee.'],
    ],
  },
  {
    slug: 'statfox', brand: 'Statfox', repo: 'web-analytics', price: 49, icon: '🦊',
    tagline: 'Privacy-first web analytics on your own server. Unlimited sites, no cookies, no monthly bill.',
    oneliner: 'Self-hosted, cookie-free web analytics — unlimited sites & traffic, one clean dashboard.',
    competitor: 'Plausible', compPrice: '$9–19/mo', compYr: 108,
    heroLead: 'Plausible charges $9–19/month, tiered by your traffic, forever. Google Analytics is "free" — paid for with your visitors\' data and your consent banner. Statfox is a lightweight analytics server you run yourself: one <2KB script tag, one dashboard for every site you own, no cookies, no consent banner, no data leaving your server.',
    features: [
      ['🪶', '< 2KB tracking snippet', 'One deferred script tag. Cookie-free and GDPR-friendly — no consent banner needed.'],
      ['🕵️', 'Uniques without cookies', 'Daily-rotating salted hash of IP + user agent. Raw IPs are never stored; yesterday\'s salt is deleted so hashes can\'t be linked across days.'],
      ['🌐', 'Unlimited sites', 'Track every client site from one dashboard — no per-site pricing, no traffic tiers.'],
      ['📊', 'The numbers that matter', 'Visitors, pageviews, bounce rate, visit duration — each compared to the previous period.'],
      ['🧭', 'Full breakdowns', 'Top pages, grouped referrers (Google, HN, Reddit, X…), countries, devices, browsers, OS, and UTM source/medium/campaign.'],
      ['⚡', 'Realtime + SPA-aware', 'Visitors in the last 5 minutes, live. pushState/replaceState navigation tracked automatically; custom events via statfox(\'signup\').'],
      ['🔗', 'Client-shareable dashboards', 'One toggle mints a tokenized read-only dashboard URL you can send to clients. Revoke any time.'],
      ['🗄️', 'One process, one SQLite file', 'Node + better-sqlite3, configurable retention pruning. Runs happily on a $5 VPS.'],
    ],
    compRows: [
      ['Price', '$49 once', '$9–19/month, tiered by traffic'],
      ['Cost over 3 years', '$49', '~$324–684'],
      ['Sites included', 'Unlimited', 'Tiered'],
      ['Traffic limits', 'None — it\'s your hardware', '10k–100k pageviews/mo per tier'],
      ['Cookies / consent banner', 'None needed', 'None needed'],
      ['Data ownership', 'Your server, your SQLite file', 'Their cloud (or complex self-host)'],
      ['Client share links', 'Yes, tokenized', 'Yes'],
      ['Source code', 'MIT, yours', 'Open source (AGPL), hosted paid'],
    ],
    payback: 'Under 3 months of a Plausible Growth plan pays for Statfox — then analytics on every site you\'ll ever build is free.',
    steps: [
      ['Buy once on Whop', 'One-time $49 for the packaged version with 1-click setup and updates.'],
      ['Deploy to a $5 VPS', 'docker compose up -d, point analytics.yourdomain.com at it, put free Cloudflare in front and country breakdowns light up automatically. Desktop mode works for checking numbers locally.'],
      ['Paste one script tag', 'Add a site in the dashboard, copy the snippet, paste it into your site\'s head. Numbers start flowing immediately.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/web-analytics, always. $49 buys the packaged version, 1-click setup and updates.'],
      ['Is it really GDPR-friendly without a banner?', 'Yes — no cookies, no localStorage, no fingerprinting. Uniqueness is a daily-rotating salted hash computed in memory; raw IPs are never written to disk and old salts are deleted, so a visitor hash is meaningless after 24 hours.'],
      ['Do I need a server?', 'For public sites, yes — the collect endpoint must be reachable from your visitors\' browsers, so budget a $5 VPS. That still costs less per year than most Plausible tiers, and it can host half this suite at once.'],
      ['What doesn\'t it do vs GA4?', 'Honestly: no funnels, no e-commerce revenue attribution, no Google Ads integration, no BigQuery export. Statfox covers the numbers most site owners actually check — traffic, sources, pages, countries, UTMs, custom events. If you live in GA4\'s advertising reports, keep GA4.'],
      ['Can I track single-page apps?', 'Yes — the snippet hooks pushState, replaceState and popstate automatically, and you can fire custom events like statfox(\'signup\') from anywhere.'],
    ],
  },
  {
    slug: 'shipnotes', brand: 'Shipnotes', repo: 'changelog-roadmap', price: 49, icon: '🚢',
    tagline: 'Changelog, public roadmap and feature-request voting — self-hosted, one-time price.',
    oneliner: 'Self-hosted changelog + roadmap + feature voting with email subscribers and an embeddable widget.',
    competitor: 'Canny', compPrice: '$79/mo', compYr: 948,
    heroLead: 'Canny charges $79/month — $948 a year — to show your users what you shipped and let them vote on what\'s next. Shipnotes is the same loop on your own $5 VPS: a Markdown changelog, a Planned / In Progress / Shipped roadmap, anonymous feature voting, email subscribers and an embeddable "What\'s new" bell, with all of it in one SQLite file you own.',
    features: [
      ['📰', 'Public changelog', 'Write posts in Markdown, tag them New / Improved / Fixed, publish with one click. Valid RSS 2.0 feed included.'],
      ['🗺️', 'Public roadmap board', 'Planned / In Progress / Shipped columns, sorted by votes, so users can see where things stand.'],
      ['💡', 'Feature requests + voting', 'Visitors submit ideas and upvote — one vote per visitor, no account or signup wall — with comment threads.'],
      ['🛡️', 'Moderation that scales', 'Approve, decline with a public reason, or merge duplicates — votes carry over and are deduped.'],
      ['📧', 'Email subscribers', 'Bring your own SMTP; publishing a post emails every subscriber with one-click unsubscribe.'],
      ['🔔', 'Embeddable "What\'s new" widget', 'One script tag adds a bell with an unread badge and a dropdown of your latest posts to any site.'],
      ['🎛️', 'Fast admin dashboard', 'Dark, keyboard-friendly — posts, requests, subscribers and settings in one place.'],
      ['💾', 'One SQLite file', 'Trivial backups, no external services, zero telemetry.'],
    ],
    compRows: [
      ['Price', '$49 once', '$79/month ($948/yr)'],
      ['Cost over 3 years', '$49', '~$2,844'],
      ['Changelog + roadmap + voting', 'Yes', 'Yes'],
      ['Anonymous voting (no signup wall)', 'Yes', 'No'],
      ['"What\'s new" widget', 'Included', 'Higher tiers'],
      ['Email notifications', 'Yes, via your own SMTP', 'Yes, their sender'],
      ['Your data', 'One SQLite file on your box', 'Their cloud'],
      ['Source code', 'MIT, yours', 'Closed'],
    ],
    payback: 'Canny costs $79 every month. Shipnotes pays for itself in 19 days — then your changelog is free for the life of your product.',
    steps: [
      ['Buy once on Whop', 'One-time $49 for the packaged version with updates and setup support.'],
      ['Deploy it', 'docker compose up -d on a $5 VPS for a public changelog at updates.yourapp.com — or run desktop mode to try it first.'],
      ['Ship, post, let users vote', 'Write a Markdown post, tag it, publish — subscribers get emailed, the widget badge lights up, and feature requests collect votes while you sleep.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/changelog-roadmap. $49 buys the packaged version, 1-click setup and updates.'],
      ['Do voters need accounts?', 'No — and that\'s deliberate. Canny puts votes behind a signup wall; Shipnotes uses a per-visitor token (one vote each, repeat votes rejected server-side). Lower friction means you hear from far more of your users.'],
      ['What doesn\'t it have vs Canny?', 'Honestly: no Jira/Slack/Intercom integrations, no user segmentation or revenue-weighted prioritization, no SSO-identified voters. Shipnotes is the core loop — changelog, roadmap, voting, email — done well. If your PM team lives in Canny\'s integrations, Canny earns its price.'],
      ['Does the widget slow my site down?', 'No — it\'s one small deferred script tag that renders a bell with an unread badge. You can attach it to your own button with data-target and theme it with data-accent.'],
      ['Do I need a server?', 'For a public changelog, yes — a $5 VPS with the included Docker setup. Desktop mode runs the identical app locally for evaluation and drafting.'],
    ],
  },
  {
    slug: 'hearback', brand: 'Hearback', repo: 'feedback-widget', price: 29, icon: '🎧',
    tagline: 'Drop-in feedback & NPS widget, self-hosted. Unlimited responses, one-time price.',
    oneliner: 'Self-hosted feedback + NPS widget with an inbox, dashboard and CSV export — unlimited responses.',
    competitor: 'Hotjar', compPrice: '$32/mo', compYr: 384,
    heroLead: 'Hotjar charges $32/month for surveys with a 500-response cap on the entry plan. Feedbackfish is $29 every month. Hearback is the same drop-in widget — floating button, emoji ratings, NPS surveys, an inbox with a dashboard — running on your server, with your data, for a one-time $29.',
    features: [
      ['⚡', 'One-line embed', 'A single script tag. Self-contained JS + CSS in a shadow DOM, so your site\'s styles never leak in and the widget never leaks out.'],
      ['😀', 'Feedback form', '1–5 emoji rating, Issue / Idea / Praise category, message, optional reply email.'],
      ['📈', 'NPS surveys', 'The classic 0–10 with a follow-up question — shown once per visitor with a frequency cap enforced in the browser and on the server.'],
      ['🧾', 'Auto-captured context', 'Page URL, user agent, viewport, referrer and an anonymous visitor token arrive with every response.'],
      ['📥', 'An inbox that works', 'Filter by mode, category, rating and status; full-text search; detail drawer; new → in progress → resolved workflow.'],
      ['📊', 'NPS dashboard', 'Live score, promoter/passive/detractor breakdown, weekly trend chart.'],
      ['🎨', 'Widget designer', 'Accent color, position, button/panel/thank-you copy and NPS timing — with live preview.'],
      ['🔒', 'Yours, entirely', 'SQLite storage, CSV export, BYO-SMTP email alerts, per-IP rate limiting + honeypot spam protection, zero telemetry.'],
    ],
    compRows: [
      ['Price', '$29 once', '$32/month ($384/yr)'],
      ['Cost over 3 years', '$29', '~$1,152'],
      ['Response limits', 'None', '500/mo on entry plan'],
      ['NPS surveys + dashboard', 'Yes', 'Yes'],
      ['Your data on your server', 'Yes', 'No'],
      ['Works behind a VPN / intranet', 'Yes', 'No'],
      ['Cookie-banner headaches', 'None — first-party', 'Third-party scripts'],
      ['Source code', 'MIT, yours', 'Closed'],
    ],
    payback: 'One month of Hotjar costs more than Hearback does once. Everything after day 28 is free.',
    steps: [
      ['Buy once on Whop', 'One-time $29 for the packaged version with 1-click setup and updates.'],
      ['Create a project, paste the snippet', 'Copy the embed from the Widget tab into any site — the shadow-DOM widget can\'t clash with your CSS.'],
      ['Read, triage, act', 'Responses land in your inbox with full context; NPS trends chart themselves; export everything to CSV whenever you like.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/feedback-widget. $29 buys the packaged version, 1-click setup and updates.'],
      ['Does it do heatmaps or session recordings?', 'No — and we\'ll be straight about that. Heatmaps and recordings are Hotjar\'s other half, and Hearback doesn\'t attempt them. If you need to watch session replays, keep Hotjar. If what you actually use is surveys and feedback, Hearback covers it for 1/12th of one year\'s bill.'],
      ['Are responses really unlimited?', 'Yes — they\'re rows in your own SQLite file. Hotjar\'s entry plan caps you at 500 survey responses a month; your disk is the only cap here.'],
      ['Will the widget break my site\'s styles?', 'No — everything renders inside a shadow DOM, so your CSS and the widget\'s can\'t touch each other. The whole thing is ~9 KB of dependency-free vanilla JS.'],
      ['Do I need a server?', 'For public sites, yes — a $5 VPS with the included Docker setup. It also works on intranets and behind VPNs, where third-party tools like Hotjar can\'t go at all.'],
    ],
  },
  {
    slug: 'docwell', brand: 'Docwell', repo: 'knowledge-base', price: 29, icon: '📚',
    tagline: 'A complete self-hosted help center — markdown in, branded SEO-ready docs out.',
    oneliner: 'Self-hosted knowledge base with instant FTS5 search, helpful-vote analytics and full SEO.',
    competitor: 'GitBook', compPrice: '$79/mo (Premium)', compYr: 948,
    heroLead: 'GitBook Premium runs $79/site/month. HelpScout Docs starts at $22/user/month inside a bundle. Docwell is a complete help center on your own hardware: write articles in Markdown with a live split-pane preview, organize collections and categories, and give customers a fast, branded, SEO-ready site with instant full-text search — for $29, once.',
    features: [
      ['🎨', 'Branded public help center', 'Your logo, brand color and hero search box — no "Powered by" badge to pay to remove.'],
      ['⚡', 'Instant FTS5 search', 'Search-as-you-type with highlighted snippets, powered by SQLite FTS5.'],
      ['✍️', 'Markdown editor with live preview', 'Split-pane editing rendered by the exact same pipeline as the public site — plus paste-to-upload images.'],
      ['🗂️', 'Collections → categories → articles', 'Reordering, slug control, and a draft / published workflow — drafts are invisible and excluded from search.'],
      ['🔗', 'Internal links done right', '[[article-slug]] wikilinks plus hand-picked related articles, auto table of contents, prev/next navigation.'],
      ['👍', 'Helpful votes + feedback report', 'One vote per visitor, optional comment on a downvote, and a report showing your worst-scoring articles first — so you know exactly what to fix.'],
      ['🔍', 'SEO done right', 'Meta descriptions, OG tags, sitemap.xml, robots.txt, canonical URLs, clean URLs, smart 404s that suggest close articles.'],
      ['🗄️', 'One SQLite file', 'Server-rendered public pages (zero JS framework), Docker included, desktop mode for offline writing, zero telemetry.'],
    ],
    compRows: [
      ['Price', '$29 once', '$79/site/month (Premium)'],
      ['Cost over 3 years', '$29', '~$2,844'],
      ['Custom branding', 'Free', 'Higher tiers'],
      ['Remove "Powered by"', 'It\'s your code', 'Paid'],
      ['Full-text search', 'FTS5, instant', 'Yes'],
      ['Helpful-vote analytics', 'Yes, with worst-first report', 'Limited'],
      ['Works offline / air-gapped', 'Yes', 'No'],
      ['Your data', 'Your server, one SQLite file', 'Their cloud'],
    ],
    payback: 'Docwell costs a third of one month of GitBook Premium. It pays for itself before your first article is finished.',
    steps: [
      ['Buy once on Whop', 'One-time $29 for the packaged Windows installer with 1-click setup and updates.'],
      ['Write your docs', 'Markdown with live split-pane preview, paste-in images, wikilinks and a draft workflow — desktop mode works fully offline.'],
      ['Publish on your domain', 'docker compose up -d on a $5 VPS, point help.yourproduct.com at it — SEO meta, sitemap and clean URLs are already done.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/knowledge-base. $29 buys the signed installer, 1-click setup and updates.'],
      ['Is the public site fast?', 'Yes — it\'s server-rendered plain HTML with no JS framework, which is also why the SEO story is so clean. Search is the only scripted part, and it\'s instant vanilla JS over FTS5.'],
      ['What doesn\'t it do vs GitBook?', 'Honestly: no git-repo sync, no AI answers, no multi-language localization, no multi-author roles — the admin is single-password. GitBook is genuinely better for open-source API docs maintained from a repo by a team. Docwell is better for the product help center you write and own.'],
      ['Can I see which articles are failing?', 'Yes — the feedback report sorts worst-scoring articles first with every thumbs-down comment attached. It\'s the single most useful page in the app.'],
      ['Do I need a server?', 'For a public help center, yes — a $5 VPS with the included Docker setup. Desktop mode runs the whole thing as a Windows app for writing and internal use.'],
    ],
  },
  {
    slug: 'chatlet', brand: 'Chatlet', repo: 'live-chat', price: 49, icon: '💬',
    tagline: 'The live-chat bubble you own — unlimited agents, unlimited sites, no per-seat pricing.',
    oneliner: 'Self-hosted live chat — real-time widget, agent dashboard, canned replies, offline messages.',
    competitor: 'Crisp', compPrice: '$95/mo (Plus)', compYr: 1140,
    heroLead: 'Crisp\'s team plan is $95/month — $1,140 a year. Intercom bills per seat, plus usage. Chatlet is the same chat bubble in the corner of your site, except you host it: one tiny Node server, one SQLite file, unlimited sites, unlimited agents, unlimited conversations, and no branding-removal fee because there\'s no branding.',
    features: [
      ['⚡', 'One-line embed', 'A single script tag. Shadow-DOM widget (~9 KB of dependency-free JS), so your site\'s CSS can\'t break it.'],
      ['🔌', 'Real-time over WebSockets', 'Automatic reconnect, an outgoing message queue, and a transparent HTTP-polling fallback when corporate firewalls block WS.'],
      ['🎛️', 'Agent dashboard', 'Live-updating inbox with open/closed states and unread badges, typing indicators both ways, sound + browser notifications.'],
      ['🪪', 'Visitor context sidebar', 'Current page, referrer, browser and full past-conversation history beside every chat.'],
      ['⌨️', 'Canned responses', 'Type /shortcut in the composer to fire saved replies instantly — full CRUD in the dashboard.'],
      ['🌙', 'Offline mode', 'No agent online? The widget switches to "leave a message", flags it in your inbox and optionally emails you via your own SMTP.'],
      ['🌐', 'Multiple sites, one install', 'Every site you run gets its own embed snippet from the same server. Transcripts download as text files.'],
      ['🔒', '100% local & private', 'SQLite storage, visitor identity persisted client-side, zero telemetry, zero third-party calls.'],
    ],
    compRows: [
      ['Price', '$49 once', '$95/month Plus plan ($1,140/yr)'],
      ['Cost over 3 years', '$49', '~$3,420'],
      ['Agents', 'Unlimited', 'Per-plan limits'],
      ['Sites', 'Unlimited', 'Per-plan limits'],
      ['Remove branding', 'There is none', 'Paid'],
      ['Canned responses', 'Included', 'Paid tier'],
      ['Your data', 'Your server, one SQLite file', 'Their cloud'],
      ['Source code', 'MIT, yours', 'Closed'],
    ],
    payback: 'Chatlet pays for itself in under 3 weeks vs Crisp\'s team plan — then live chat is free for as long as you run a website.',
    steps: [
      ['Buy once on Whop', 'One-time $49 for the packaged version — Windows desktop app plus one-command VPS deploy.'],
      ['Deploy where visitors can reach it', 'docker compose up -d on a $5 VPS behind your reverse proxy (WebSocket upgrade passed through). Desktop mode is perfect as the always-on agent console.'],
      ['Paste the snippet, start chatting', 'Copy the embed from Sites, paste it before </body>, and conversations land in your dashboard in real time.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/live-chat. $49 buys the packaged version, 1-click setup and updates.'],
      ['Does it have chatbots or AI answers?', 'No — Chatlet is human-to-human live chat done properly: real-time delivery, typing indicators, canned responses, offline messages. Intercom\'s Fin-style AI agents and workflow bots are genuinely beyond its scope; if you need those, Intercom earns its (considerable) price.'],
      ['Do I need a server?', 'For visitors on the public internet, yes — the widget needs a public address, so budget a $5 VPS. Desktop mode runs the same server locally and doubles as your agent console.'],
      ['Is there a mobile app for agents?', 'Not yet — honestly. The dashboard is responsive and works in a phone browser, with sound and browser notifications, but there\'s no native iOS/Android agent app like Crisp\'s.'],
      ['What happens when no agent is online?', 'The widget flips to "leave a message" automatically. Messages arrive flagged in your inbox, and Chatlet can email you via your own SMTP so nothing sits unread.'],
    ],
  },
  {
    slug: 'boardly', brand: 'Boardly', repo: 'boardly-kanban', price: 19, icon: '📋',
    tagline: 'The self-hosted Trello replacement — unlimited boards, your data in one SQLite file.',
    oneliner: 'Self-hosted kanban — drag & drop boards, checklists, labels, attachments, full JSON export.',
    competitor: 'Trello', compPrice: '$5/user/mo', compYr: 60,
    heroLead: 'Trello charges $5 per user per month — a 10-person team pays $600 every year, forever, for lists with cards on them. Boardly is the same kanban workflow on your hardware: unlimited boards, as many people as your server allows, and your data in a single SQLite file you can copy, back up and export any time.',
    features: [
      ['🗂️', 'Multiple boards', 'Color themes, emoji icons, starred favorites — organize work, clients or your whole life.'],
      ['✋', 'Drag & drop everything', 'Reorder lists, drag cards between lists — order persists exactly where you dropped it.'],
      ['🃏', 'Rich cards', 'Markdown descriptions, due dates with overdue highlighting, colored board-scoped labels.'],
      ['☑️', 'Checklists', 'With live progress bars right on the card front.'],
      ['📎', 'Attachments', 'Upload files straight onto cards — stored on your disk, with your limits, not a 250 MB plan cap.'],
      ['💬', 'Comments + activity log', 'Full history per card and per board.'],
      ['🔎', 'Filter & search', 'By label, by due date (overdue / this week / none), plus full-text card search and keyboard shortcuts.'],
      ['📦', 'Full-fidelity export/import', 'One-click JSON round trip including attachment bytes — for backups or moving boards between installs. Archive instead of delete, restore anytime.'],
    ],
    compRows: [
      ['Price', '$19 once', '$5/user/month (Standard)'],
      ['10-person team, 3 years', '$19 total', '$1,800'],
      ['Boards', 'Unlimited', 'Limited on free tier'],
      ['Attachments', 'Your disk, your limits', '250 MB/file cap, plan-gated'],
      ['Data ownership', 'SQLite file on your box', 'Atlassian\'s cloud'],
      ['Works offline / air-gapped', 'Yes', 'No'],
      ['Full JSON export', 'One click, attachments included', 'Plan-gated'],
      ['Telemetry', 'None', 'Plenty'],
    ],
    payback: 'Boardly costs less than four months of a single Trello seat — for a team it pays for itself the day you install it.',
    steps: [
      ['Buy once on Whop', 'One-time $19 — one of the cheapest apps in the suite. Installer, updates and setup support included.'],
      ['Run it anywhere', 'Desktop app for personal boards, or docker compose up -d on a $5 VPS for the whole team.'],
      ['Move your boards in', 'Create lists, drag cards, attach files, tick checklists. Export everything to JSON whenever you want proof you own it.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/boardly-kanban, always. $19 buys the packaged installer, updates and setup support.'],
      ['How do team members log in?', 'One shared password protects the whole install — there are no per-user accounts, permissions or assignee fields yet. That\'s fine for small teams on a trusted server or VPN; if you need granular roles and member management, Trello still wins there.'],
      ['Does it have automations like Butler?', 'No — no rule engine, no scheduled commands. Boardly bets that most Trello boards never touch Butler, and most don\'t. If yours does, keep Trello.'],
      ['Is there a mobile app?', 'No native app — the web UI works in a phone browser when you host it on a VPS. Desktop mode is Windows-first, and the MIT source builds anywhere Electron runs.'],
      ['Can I get my data out?', 'Completely — one click exports a full-fidelity JSON file including attachment bytes, and importing it on another install reproduces your boards exactly. Try asking Trello\'s free tier for that.'],
    ],
  },
  {
    slug: 'timevault', brand: 'Timevault', repo: 'timevault-tracker', price: 29, icon: '⏱️',
    tagline: 'Time tracking for freelancers who bill clients — timers, rates and reports you own.',
    oneliner: 'Self-hosted time tracking — one-click timers, hourly rates, weekly timesheets, billable reports.',
    competitor: 'Toggl', compPrice: '$10/user/mo', compYr: 120,
    heroLead: 'Toggl charges $10 per user per month, forever, to store your timers in their cloud. Timevault is time tracking for people who bill: one-click timers that survive a browser restart, projects with clients and hourly rates, weekly timesheets, and reports that compute exactly what to invoice — on your machine or your $5 VPS.',
    features: [
      ['▶️', 'One-click timer', 'Description, project, tags, Enter to start. The timer is server state — reload, close the tab, restart your browser, it keeps counting.'],
      ['✍️', 'Manual entries', 'Start + end times, or start + duration ("1:30", "1.5", "90m"). Stop, discard mistakes, or one-click continue any previous entry.'],
      ['💼', 'Projects, clients & rates', 'Colors, billable flags and hourly rates per project. Archive finished projects without losing history.'],
      ['📆', 'Weekly timesheet', 'A 7-day grid with inline editing of descriptions and durations right in the cell.'],
      ['📊', 'Reports that invoice', 'Any range, grouped by project / client / tag / day — bar chart, donut, and exact total + billable amounts from your rates.'],
      ['⚖️', 'Report-level rounding', 'Round to the nearest 5 or 15 minutes at report time — your raw data is never touched. Bill like a law firm.'],
      ['🚨', 'Overlap detection', 'Double-booked entries get a warning badge, so your invoices survive client scrutiny.'],
      ['🔒', '100% local & private', 'SQLite file, CSV export, printable summaries, no telemetry, no account.'],
    ],
    compRows: [
      ['Price', '$29 once', '$10/user/month'],
      ['Cost over 3 years', '$29', '$360'],
      ['Your data lives', 'Your server / your PC', 'Their cloud'],
      ['Billable rates & totals', 'Yes', 'Yes'],
      ['Report rounding (5/15 min)', 'Yes', 'Paid tier'],
      ['Overlap detection', 'Yes', 'No'],
      ['Works offline', 'Yes', 'No'],
      ['Source code', 'MIT, yours', 'Closed'],
    ],
    payback: 'Three months of Toggl pays for Timevault outright — after that, every tracked hour is pure margin.',
    steps: [
      ['Buy once on Whop', 'One-time $29 for the packaged Windows installer with everything pre-built.'],
      ['Set up projects and rates', 'Clients, colors, billable flags and hourly rates — archive projects when engagements end.'],
      ['Track, then invoice from the report', 'Run timers or enter time manually, open a report for the billing period, apply 15-minute rounding, and read the exact billable amount off the screen.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/timevault-tracker. $29 buys the packaged installer, 1-click setup and updates.'],
      ['What happens to a running timer if my browser crashes?', 'Nothing — the timer is server state, not a browser widget. Reload the page an hour later and it\'s still counting from the original start.'],
      ['Is there a mobile app or idle detection?', 'No — honestly. Toggl\'s native apps, idle detection and calendar integrations are real advantages if you track from your phone all day. Timevault is browser + desktop, aimed at people who work at a computer and bill for it.'],
      ['Does rounding change my data?', 'Never — rounding is applied at report level only. Your raw entries stay exact, so you can re-run the same period at 5, 15 or no rounding.'],
      ['Is it multi-user?', 'It\'s single-workspace with one password — perfect for a freelancer or a small studio sharing one install. Per-seat team features are exactly the thing Toggl charges monthly for; if you need approval workflows, stay there.'],
    ],
  },
  {
    slug: 'streakly', brand: 'Streakly', repo: 'habit-tracker', price: 15, icon: '🔥',
    tagline: 'The desktop habit tracker you buy once — streaks, heatmaps and schedules that match real life.',
    oneliner: 'Local habit tracking with a fair streak engine, GitHub-style heatmaps and reminders.',
    competitor: 'Habitify', compPrice: '$5/mo', compYr: 60,
    heroLead: 'Habitify charges $5/month, forever, to store your checkmarks on their servers. Streakly is $15 once: habits with schedules that match real life, numeric goals, a streak engine that\'s actually fair, GitHub-style heatmaps and native reminders — 100% local, zero cloud, zero telemetry. Your habits are not a subscription.',
    features: [
      ['🗓️', 'Schedules that match real life', 'Every day, specific weekdays, or N times per week — with an icon and color per habit.'],
      ['🔢', 'Numeric goals', '"8 glasses of water", "50 pushups" — increment through the day; only hitting the goal completes it, partial counts still tracked.'],
      ['🔥', 'A streak engine that\'s fair', 'Weekday-only habits survive the weekend, N-per-week habits count weekly quotas, and today doesn\'t break your streak just because it isn\'t done yet.'],
      ['🏖️', 'Vacation mode', 'Skip days freeze your streaks instead of killing them.'],
      ['🟩', 'GitHub-style heatmaps', 'A year heatmap per habit plus an all-habits month view with per-day dots.'],
      ['⏰', 'Reminders', 'Native OS notifications at the times you choose.'],
      ['📊', 'Stats + notes', 'Current & best streak, total completions, completion % over 30/90/365 days — and a journal line on any check-in.'],
      ['💾', 'Your data is a JSON file', 'Human-readable, in your user folder — JSON export/import for backup, CSV for spreadsheets. No network calls at all.'],
    ],
    compRows: [
      ['Price', '$15 once', '$5/mo ($60/yr, forever)'],
      ['Cost after 3 years', '$15', '$180'],
      ['Your data lives', 'On your machine', 'Their cloud'],
      ['Account required', 'No', 'Yes'],
      ['Streak freeze / vacation mode', 'Yes', 'Premium feature'],
      ['N-times-per-week quotas', 'Yes', 'Yes'],
      ['Export your data', 'JSON + CSV, one click', 'Limited'],
      ['Telemetry', 'None', 'Analytics SDKs'],
    ],
    payback: 'Three months of Habitify costs the same as Streakly does once — your streaks shouldn\'t have a renewal date.',
    steps: [
      ['Buy once on Whop', 'One-time $15 — the cheapest app in the suite, tied with Deepdesk.'],
      ['Create your habits', 'Icon, color, schedule and optional numeric goal — reorder your today list by dragging.'],
      ['Check in daily', 'Tick habits (or count reps), keep streaks alive fairly, and watch the year heatmap fill in.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/habit-tracker. $15 buys the packaged Windows installer and updates.'],
      ['Why is the streak engine "fair"?', 'Because most trackers punish you for their own bad math. In Streakly, a weekdays-only habit doesn\'t break over the weekend, an N-per-week habit counts weekly quotas across week boundaries, skip days freeze streaks, and an unfinished today never kills a streak prematurely. The engine is a pure zero-dependency module with its own test suite.'],
      ['Is there a phone app or sync?', 'No — Streakly is desktop-first with no cloud, which is exactly why it can promise zero network calls. Your entire history is one JSON file; sync it yourself via Dropbox, Drive or Syncthing if you want it on two machines. If phone-first tracking matters most, Habitify is the better fit.'],
      ['Do reminders work?', 'Yes — native OS notifications at whatever times you set per habit.'],
      ['What if the app disappears?', 'Nothing happens — your data is a human-readable JSON file on your own disk, and the MIT source builds the app anywhere Electron runs.'],
    ],
  },
  {
    slug: 'deepdesk', brand: 'Deepdesk', repo: 'focus-dashboard', price: 15, icon: '🎯',
    tagline: 'A local-first deep-work dashboard — Pomodoro, intents, ambient noise, streaks. No account.',
    oneliner: 'Pomodoro engine, session intents, floating mini timer, generated ambient noise & focus stats.',
    competitor: 'Centered', compPrice: '~$10/mo', compYr: 120,
    heroLead: 'Focus apps like Centered and Session charge $5–10/month for a timer, a task list and some rain sounds. Deepdesk is the whole deep-work loop — a Pomodoro engine, session intents, per-task tallies, an always-on-top mini timer, procedurally generated ambient noise and a streak dashboard — stored on your machine, purchased exactly once.',
    features: [
      ['🍅', 'Pomodoro engine', 'Configurable focus / short break / long break lengths, auto-cycling, long break after every N sessions, pause and skip.'],
      ['🧭', 'Session intents', 'Answer "what are you working on?" before each session — every intent lands in your session log.'],
      ['✅', 'Tasks with pomodoro tallies', 'Add tasks, pick the active one, and watch its 🍅 count grow as you complete sessions.'],
      ['🪟', 'Always-on-top mini timer', 'A frameless, draggable floating widget with a live progress ring — hover to expand pause / skip / open controls.'],
      ['🌧️', 'Generated ambient noise', 'White, pink and brown noise plus procedural rain, synthesized mathematically in real time — per-source mix sliders, no audio files, no streaming.'],
      ['🔔', 'Gentle transitions', 'OS notification plus a two-note chime synthesized live with WebAudio.'],
      ['📈', 'Daily dashboard', 'Focus minutes today and this week, day streak, 30-day history chart, full session log with intents.'],
      ['🔒', 'Local-first', 'Settings, tasks and history are plain JSON in your user folder. No account, no cloud, no telemetry.'],
    ],
    compRows: [
      ['Price', '$15 once', '~$10/month'],
      ['Cost over 2 years', '$15', '~$240'],
      ['Account required', 'Never', 'Yes'],
      ['Works offline', 'Always', 'Partly'],
      ['Pomodoro + intents + tasks', 'Yes', 'Yes'],
      ['Floating mini timer', 'Yes', 'Yes'],
      ['Ambient noise', 'Generated locally', 'Streamed'],
      ['Source code', 'MIT, yours', 'Closed'],
    ],
    payback: 'Deepdesk costs six weeks of Centered — and it keeps working after every focus startup pivots or shuts down.',
    steps: [
      ['Buy once on Whop', 'One-time $15 for the packaged Windows installer — lifetime updates included.'],
      ['Set an intent, start a session', 'Pick your active task, answer "what are you working on?", and let the mini timer float over whatever you\'re doing.'],
      ['Watch the streak build', 'Focus minutes, day streaks and a 30-day chart accumulate in your local dashboard — with every intent logged.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/focus-dashboard. $15 buys the signed installer, auto-shortcuts and zero setup.'],
      ['How is the ambient noise generated?', 'Mathematically, in real time — white/pink/brown noise and droplet-synthesized rain as pure sample-buffer math through WebAudio. No audio files are shipped and nothing streams, which is why it works offline forever.'],
      ['Does it block distracting websites or apps?', 'No — Deepdesk is a timer, intent and stats tool, not a blocker. Pair it with a hosts-file blocker if you need hard enforcement. Centered\'s coaching nudges and Flow music are also things Deepdesk deliberately doesn\'t do.'],
      ['Can paused time leak into a session?', 'No — the Pomodoro brain is a pure tick-driven state machine fed wall-clock deltas. Pausing simply stops feeding ticks, so paused minutes can\'t count. The engine has its own test suite.'],
      ['Is my history private?', 'Completely — everything persists as plain JSON under your OS user-data folder. Yours to back up, grep or delete.'],
    ],
  },
  {
    slug: 'quillpad', brand: 'Quillpad', repo: 'quillpad-notes', price: 29, icon: '🪶',
    tagline: 'Local-first markdown notes — your knowledge base is a folder of plain .md files you own.',
    oneliner: 'Fast desktop notes with wikilinks, backlinks, tags, daily notes and global quick capture.',
    competitor: 'Notion', compPrice: '$12/mo per seat', compYr: 144,
    heroLead: 'Notion charges $12/month per seat and keeps your notes in their cloud, in their format. Obsidian is free but charges monthly for sync. Quillpad is a fast, beautiful desktop notes app where every note is a real markdown file in a folder you picked — wikilinks, backlinks, tags, daily notes, global quick capture — and your entire "knowledge base" outlives every notes startup.',
    features: [
      ['📁', 'Your vault is just a folder', 'Notes are real .md files, folders are folders. Edit them in any other app — Quillpad watches the disk and refreshes live.'],
      ['✍️', 'Live-styled markdown editor', 'CodeMirror 6 with inline preview styling — sized headings, rendered bold/italic, highlighted code. Ctrl+E toggles full preview.'],
      ['🔗', '[[Wikilinks]] + backlinks', 'Type [[ for fuzzy autocomplete over every note; aliases supported; missing notes are created on click. Every note shows who links to it, with context.'],
      ['#️⃣', 'Tags', '#hashtags anywhere appear in the sidebar — click to filter.'],
      ['🔎', 'Full-text search + quick switcher', 'Instant search with highlighted matches across the vault; Ctrl+P jumps to any note, recent first.'],
      ['📅', 'Daily notes', 'Ctrl+D opens (or creates) today\'s daily/YYYY-MM-DD.md.'],
      ['⚡', 'Global quick capture', 'Ctrl+Shift+N from anywhere in Windows pops a tiny window; Enter appends to inbox.md.'],
      ['🔒', '100% local', 'No account, no cloud, no database, no telemetry, no network calls — ever.'],
    ],
    compRows: [
      ['Price', '$29 once', '$12/mo per seat'],
      ['Cost after 3 years', '$29', '$432'],
      ['Your data', 'Plain .md files in your folder', 'Their cloud, their format'],
      ['Works offline', 'Always', 'Partially'],
      ['Account required', 'No', 'Yes'],
      ['Export needed to leave', 'Never — it\'s already files', 'Yes'],
      ['Wikilinks + backlinks', 'Yes', 'Linked mentions'],
      ['Telemetry', 'None', 'Yes'],
    ],
    payback: 'Two and a half months of one Notion seat pays for Quillpad — and your notes stop being hostages.',
    steps: [
      ['Buy once on Whop', 'One-time $29 for the signed one-click Windows installer with auto-updates.'],
      ['Point it at a folder', 'Use the starter vault under Documents or pick any existing folder of markdown — it just works, live.'],
      ['Write, link, capture', 'Wikilinks with autocomplete, backlinks with context, daily notes on Ctrl+D, and quick capture from anywhere in Windows.'],
    ],
    faq: [
      ['Is it really free on GitHub?', 'Yes — MIT source at github.com/bensblueprints/quillpad-notes, always. $29 buys the signed installer with auto-updates.'],
      ['How do I sync between machines?', 'Your vault is a plain folder, so any file sync works: Dropbox, Google Drive, Syncthing, git. There\'s no built-in sync service — that\'s a feature, not a gap: it\'s why there\'s no account and no monthly fee. If you want turnkey encrypted mobile sync, Obsidian Sync is good at that.'],
      ['Can it replace Notion databases?', 'No — Quillpad is notes, links and tags, not tables, kanbans and formulas. If your workspace is really a database app, Notion earns its seat fee. If it\'s actually a pile of documents, files are better.'],
      ['What happens if Quillpad disappears?', 'Nothing — your notes are already plain markdown files in your own folder. Open them in anything. That\'s the whole point.'],
      ['Is there a mobile app?', 'No — Quillpad is a desktop app (Windows installer; MIT source builds on macOS/Linux). On your phone, any markdown editor pointed at your synced folder works with the same files.'],
    ],
  },
];
