// slug -> local onetime-suite folder name, where products.js "repo" drifted from the
// actual folder name on disk (renamed/rebranded after the repo field was set).
module.exports = {
  clipdeck: 'screen-recorder',
  boardly: 'kanban',
  timevault: 'time-tracker',
  quillpad: 'md-notes',
  pingcron: 'cron-monitor',
  hookscope: 'webhook-inspector',
  snapfleet: 'screenshot-api',
  wrangle: 'data-toolbox',
  vaultkeeper: 'db-backup',
  queuecraft: 'waitlist-referral',
  bravowall: 'testimonial-wall',
  hawkwatch: 'price-monitor',
  postbird: 'email-campaigns',
  keymaster: 'license-server',
  castport: 'podcast-host',
  inkpress: 'md-blog',
  feedloft: 'rss-reader',
  reelsnag: 'clip-grabber',
  voicebarn: 'tts-studio',
  droplink: 'file-transfer',
  snipvault: 'snippet-manager',
  textract: 'ocr-tool',
  inkseal: 'e-signature',
  overlayr: 'stream-overlays',
  signboard: 'digital-signage',
  serpdeck: 'rank-tracker',
  chatterbox: 'comment-widget',
  ledgerly: 'expense-tracker',
};
